project:
  type: website
  output-dir: docs
  
website: 
  title: "Notes and Projects about Statistics😄"
  navbar:
    left:
      - href: https://yuuuulu.github.io/
        text: yuuuulu homepage
      - href: index.qmd
        text: Practice Project List
      - href: https://yuuuulu.github.io/MathematicalModeling2025/
        text: 2025 MMC
      - href: https://yuuuulu.github.io/mixed-model-repeated-measures-depression-clinical-data/
        text: Biostat contest using Mixed Model
      - href: 2421874.pdf
        text: 2024 MMC
      - href: 2024surf.qmd
        text: SURF 2024
      - href: https://yuuuulu.github.io/2025SURF/
        text: SURF2025
      - href: distribution transformation.qmd
        text: Mathematical Statistics
      - href: MTH203Project.qmd
        text: MIP-Algorithm-Development
     ## - href: APH103_Final_Report.pdf
       # text: Survey Sampling Report with codes
      
      #- href: sequence.qmd
       # text: sequence
      #- href: Lagrange.qmd
       # text: lasso and Lagrange method
      #- href: understand directional derivative deeply.qmd
        #text: Directional Derivative
      
format: 
  html: 
    theme: cosmo
    toc: true