project:
  type: website
  output-dir: docs
  
website: 
  title: "Notes and Projects about Statistics😄"
  navbar:
    left:
      - href: https://yuuuulu.github.io/
        text: yuuuulu homepage
      - href: index.qmd
        text: 2024 summer SURF---Survival Analysis in Poisoning
      - href: https://yutong04.github.io
        text: our work of 2024 summer SURF
      - href: surf2024.html
        text: codes of 2024 summer SURF
      - href: distribution transformation.qmd
        text: Mathematical Statistics
      - href: SurveySampling.qmd
        text: Survey Sampling
      - href: APH103_Final_Report.pdf
        text: Survey Sampling Report with codes
      
      #- href: sequence.qmd
       # text: sequence
      #- href: Lagrange.qmd
       # text: lasso and Lagrange method
      #- href: understand directional derivative deeply.qmd
        #text: Directional Derivative
      
format: 
  html: 
    theme: cosmo
    toc: true