<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Notes and Projects about Statistics😄 - APH103-SurveySampling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Notes and Projects about Statistics😄</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://yuuuulu.github.io/"> 
<span class="menu-text">yuuuulu homepage</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">2024 summer SURF—Survival Analysis in Poisoning</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://yutong04.github.io"> 
<span class="menu-text">our work of 2024 summer SURF</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./surf2024.html"> 
<span class="menu-text">codes of 2024 summer SURF</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./distribution transformation.html"> 
<span class="menu-text">Mathematical Statistics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./SurveySampling.html" aria-current="page"> 
<span class="menu-text">Survey Sampling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./APH103_Final_Report.pdf"> 
<span class="menu-text">Survey Sampling Report with codes</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#thanks-to-dr.-haojin-zhou-for-teaching-me-this-course." id="toc-thanks-to-dr.-haojin-zhou-for-teaching-me-this-course." class="nav-link active" data-scroll-target="#thanks-to-dr.-haojin-zhou-for-teaching-me-this-course.">Thanks to Dr.&nbsp;Haojin Zhou for teaching me this course.</a></li>
  <li><a href="#reference-book" id="toc-reference-book" class="nav-link" data-scroll-target="#reference-book">Reference Book:</a></li>
  <li><a href="#an-important-example-of-survey-sampling" id="toc-an-important-example-of-survey-sampling" class="nav-link" data-scroll-target="#an-important-example-of-survey-sampling">An important example of Survey Sampling</a>
  <ul class="collapse">
  <li><a href="#sample-from-real-population" id="toc-sample-from-real-population" class="nav-link" data-scroll-target="#sample-from-real-population">Sample from real population</a>
  <ul class="collapse">
  <li><a href="#srp" id="toc-srp" class="nav-link" data-scroll-target="#srp">SRP</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section">5.1</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1">5.2</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2">5.3</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3">5.6</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem">Central Limit Theorem</a>
  <ul class="collapse">
  <li><a href="#limit-distribution" id="toc-limit-distribution" class="nav-link" data-scroll-target="#limit-distribution">Limit Distribution</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#this-leads-the-construction-of-confidence-interval-as-well-as-sample-size-which-is-one-of-keys-to-survey-sampling" id="toc-this-leads-the-construction-of-confidence-interval-as-well-as-sample-size-which-is-one-of-keys-to-survey-sampling" class="nav-link" data-scroll-target="#this-leads-the-construction-of-confidence-interval-as-well-as-sample-size-which-is-one-of-keys-to-survey-sampling">This leads the construction of confidence interval as well as sample size, which is one of keys to SURVEY SAMPLING</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#basic-knowledge-of-statistics" id="toc-basic-knowledge-of-statistics" class="nav-link" data-scroll-target="#basic-knowledge-of-statistics">Basic knowledge of Statistics</a>
  <ul class="collapse">
  <li><a href="#sampling-distribution" id="toc-sampling-distribution" class="nav-link" data-scroll-target="#sampling-distribution">Sampling distribution</a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#basic-knowledge-in-survey-sampling" id="toc-basic-knowledge-in-survey-sampling" class="nav-link" data-scroll-target="#basic-knowledge-in-survey-sampling">Basic knowledge in Survey sampling</a></li>
  <li><a href="#chapter-4-simple-random-sampling-srs" id="toc-chapter-4-simple-random-sampling-srs" class="nav-link" data-scroll-target="#chapter-4-simple-random-sampling-srs">Chapter 4 Simple Random Sampling (SRS)</a>
  <ul class="collapse">
  <li><a href="#estimator-for-population-mean" id="toc-estimator-for-population-mean" class="nav-link" data-scroll-target="#estimator-for-population-mean">Estimator for population mean</a></li>
  <li><a href="#estimator-for-population-total" id="toc-estimator-for-population-total" class="nav-link" data-scroll-target="#estimator-for-population-total">Estimator for population total</a>
  <ul class="collapse">
  <li><a href="#a-note-on-bounds" id="toc-a-note-on-bounds" class="nav-link" data-scroll-target="#a-note-on-bounds">A note on Bounds</a></li>
  </ul></li>
  <li><a href="#sample-size-estimates-for-population-mean-and-for-population-total" id="toc-sample-size-estimates-for-population-mean-and-for-population-total" class="nav-link" data-scroll-target="#sample-size-estimates-for-population-mean-and-for-population-total">Sample size estimates for population mean and for population total</a>
  <ul class="collapse">
  <li><a href="#fuction-in-r-for-sample-size-estimate" id="toc-fuction-in-r-for-sample-size-estimate" class="nav-link" data-scroll-target="#fuction-in-r-for-sample-size-estimate">Fuction in R for sample size estimate</a></li>
  </ul></li>
  <li><a href="#estimator-for-population-proportion" id="toc-estimator-for-population-proportion" class="nav-link" data-scroll-target="#estimator-for-population-proportion">Estimator for population proportion</a></li>
  <li><a href="#sample-size-estimate-for-population-proportion" id="toc-sample-size-estimate-for-population-proportion" class="nav-link" data-scroll-target="#sample-size-estimate-for-population-proportion">Sample size estimate for population proportion</a></li>
  <li><a href="#example-exercise" id="toc-example-exercise" class="nav-link" data-scroll-target="#example-exercise">Example Exercise</a></li>
  </ul></li>
  <li><a href="#chapter-5-stratfied-sampling" id="toc-chapter-5-stratfied-sampling" class="nav-link" data-scroll-target="#chapter-5-stratfied-sampling">Chapter 5 Stratfied Sampling</a>
  <ul class="collapse">
  <li><a href="#estimator-for-population-mean-1" id="toc-estimator-for-population-mean-1" class="nav-link" data-scroll-target="#estimator-for-population-mean-1">Estimator for population mean</a></li>
  <li><a href="#estimator-for-population-total-1" id="toc-estimator-for-population-total-1" class="nav-link" data-scroll-target="#estimator-for-population-total-1">Estimator for population total</a></li>
  <li><a href="#approximate-sample-size-with-a-fixed-bound" id="toc-approximate-sample-size-with-a-fixed-bound" class="nav-link" data-scroll-target="#approximate-sample-size-with-a-fixed-bound">Approximate Sample size with a fixed Bound</a></li>
  <li><a href="#example-exercise-1" id="toc-example-exercise-1" class="nav-link" data-scroll-target="#example-exercise-1">Example Exercise</a></li>
  </ul></li>
  <li><a href="#chapte-7-systematic-sampling" id="toc-chapte-7-systematic-sampling" class="nav-link" data-scroll-target="#chapte-7-systematic-sampling">Chapte 7 Systematic Sampling</a>
  <ul class="collapse">
  <li><a href="#estimator-for-population-mean-2" id="toc-estimator-for-population-mean-2" class="nav-link" data-scroll-target="#estimator-for-population-mean-2">Estimator for population mean</a></li>
  <li><a href="#in-k-sampling-for-mean" id="toc-in-k-sampling-for-mean" class="nav-link" data-scroll-target="#in-k-sampling-for-mean">1 in k sampling for mean</a></li>
  <li><a href="#in-k-sampling-for-total" id="toc-in-k-sampling-for-total" class="nav-link" data-scroll-target="#in-k-sampling-for-total">1 in k sampling for total</a></li>
  <li><a href="#example-exercise-2" id="toc-example-exercise-2" class="nav-link" data-scroll-target="#example-exercise-2">Example Exercise</a></li>
  </ul></li>
  <li><a href="#chapter-8-cluster-sampling" id="toc-chapter-8-cluster-sampling" class="nav-link" data-scroll-target="#chapter-8-cluster-sampling">Chapter 8 Cluster Sampling</a>
  <ul class="collapse">
  <li><a href="#notations" id="toc-notations" class="nav-link" data-scroll-target="#notations">Notations</a></li>
  <li><a href="#population-mean" id="toc-population-mean" class="nav-link" data-scroll-target="#population-mean">Population mean</a></li>
  <li><a href="#population-total" id="toc-population-total" class="nav-link" data-scroll-target="#population-total">Population total</a></li>
  <li><a href="#population-total-m-unknown" id="toc-population-total-m-unknown" class="nav-link" data-scroll-target="#population-total-m-unknown">Population total (M unknown)</a></li>
  <li><a href="#approximate-sample-size-required-to-estimate-population-mean" id="toc-approximate-sample-size-required-to-estimate-population-mean" class="nav-link" data-scroll-target="#approximate-sample-size-required-to-estimate-population-mean">Approximate sample size required to estimate population mean</a></li>
  <li><a href="#approximate-sample-size-required-to-estimate-population-total" id="toc-approximate-sample-size-required-to-estimate-population-total" class="nav-link" data-scroll-target="#approximate-sample-size-required-to-estimate-population-total">Approximate sample size required to estimate population total</a></li>
  <li><a href="#approximate-sample-size-required-to-estimate-population-total-without-m" id="toc-approximate-sample-size-required-to-estimate-population-total-without-m" class="nav-link" data-scroll-target="#approximate-sample-size-required-to-estimate-population-total-without-m">Approximate sample size required to estimate population total (without M)</a></li>
  <li><a href="#population-proportion" id="toc-population-proportion" class="nav-link" data-scroll-target="#population-proportion">Population proportion</a></li>
  <li><a href="#probabilities-proportional-to-size-pps" id="toc-probabilities-proportional-to-size-pps" class="nav-link" data-scroll-target="#probabilities-proportional-to-size-pps">Probabilities proportional to size (PPS)</a></li>
  <li><a href="#example-exercise-3" id="toc-example-exercise-3" class="nav-link" data-scroll-target="#example-exercise-3">Example Exercise</a></li>
  </ul></li>
  <li><a href="#chapter-9-two-stage-cluster-sampling" id="toc-chapter-9-two-stage-cluster-sampling" class="nav-link" data-scroll-target="#chapter-9-two-stage-cluster-sampling">Chapter 9 Two-Stage Cluster Sampling</a>
  <ul class="collapse">
  <li><a href="#advantages" id="toc-advantages" class="nav-link" data-scroll-target="#advantages">Advantages</a></li>
  <li><a href="#how-to-draw" id="toc-how-to-draw" class="nav-link" data-scroll-target="#how-to-draw">How to draw</a></li>
  <li><a href="#population-mean-1" id="toc-population-mean-1" class="nav-link" data-scroll-target="#population-mean-1">Population mean</a></li>
  <li><a href="#population-total-1" id="toc-population-total-1" class="nav-link" data-scroll-target="#population-total-1">Population total</a></li>
  <li><a href="#ratio-estimation-of-population-mean" id="toc-ratio-estimation-of-population-mean" class="nav-link" data-scroll-target="#ratio-estimation-of-population-mean">Ratio Estimation of Population Mean</a></li>
  <li><a href="#population-proportion-1" id="toc-population-proportion-1" class="nav-link" data-scroll-target="#population-proportion-1">Population proportion</a></li>
  <li><a href="#probabilities-proportional-to-size-pps-1" id="toc-probabilities-proportional-to-size-pps-1" class="nav-link" data-scroll-target="#probabilities-proportional-to-size-pps-1">Probabilities proportional to size (PPS)</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a>
  <ul class="collapse">
  <li><a href="#advantages-and-disadvantages-of-common-sampling-methods" id="toc-advantages-and-disadvantages-of-common-sampling-methods" class="nav-link" data-scroll-target="#advantages-and-disadvantages-of-common-sampling-methods">Advantages and Disadvantages of Common Sampling Methods</a>
  <ul class="collapse">
  <li><a href="#simple-random-sampling" id="toc-simple-random-sampling" class="nav-link" data-scroll-target="#simple-random-sampling">Simple Random Sampling:</a></li>
  <li><a href="#stratified-sampling" id="toc-stratified-sampling" class="nav-link" data-scroll-target="#stratified-sampling">Stratified Sampling:</a></li>
  <li><a href="#cluster-sampling" id="toc-cluster-sampling" class="nav-link" data-scroll-target="#cluster-sampling">Cluster Sampling:</a></li>
  <li><a href="#systematic-sampling" id="toc-systematic-sampling" class="nav-link" data-scroll-target="#systematic-sampling">Systematic Sampling:</a></li>
  <li><a href="#prevention-and-correction-of-sample-selection-bias" id="toc-prevention-and-correction-of-sample-selection-bias" class="nav-link" data-scroll-target="#prevention-and-correction-of-sample-selection-bias">Prevention and Correction of Sample Selection Bias</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">APH103-SurveySampling</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="thanks-to-dr.-haojin-zhou-for-teaching-me-this-course." class="level1">
<h1>Thanks to Dr.&nbsp;Haojin Zhou for teaching me this course.</h1>
</section>
<section id="reference-book" class="level1">
<h1>Reference Book:</h1>
<p>Elementary Survey Sampling, 7th Edition, by Richard L. Scheaffer, William Mendenhall III, and Richard L. Ott</p>
</section>
<section id="an-important-example-of-survey-sampling" class="level1">
<h1>An important example of Survey Sampling</h1>
<section id="sample-from-real-population" class="level2">
<h2 class="anchored" data-anchor-id="sample-from-real-population">Sample from real population</h2>
<section id="srp" class="level3">
<h3 class="anchored" data-anchor-id="srp">SRP</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sampling)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Chap 5: Sampling from Real Populations</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#5.1 Data on the population of the United States is given in Appendix C and on the data disk under USPOP. The goal is to estimate the total U.S. population in the 18–24 age group from a sample of states. The states are divided into four geographic regions. Using these regions as strata, select an appropriately sized stratified random sample of states and use their data on population in the 18- to 24-year-old group to estimate the total U.S. population in that age group. Because the total population is available from the data on all the states, check to see if your estimate is within the margin of error you established for your estimate. Compare your result with those of other students in the class.</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"/Users/luyu/Library/CloudStorage/OneDrive-Xi'anJiaotong-LiverpoolUniversity"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>USPOP <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"USPOP(3).XLS"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(USPOP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    State              Total              Section        18-24          
 Length:51          Length:51          Min.   :1.00   Length:51         
 Class :character   Class :character   1st Qu.:2.00   Class :character  
 Mode  :character   Mode  :character   Median :3.00   Mode  :character  
                                       Mean   :2.66                     
                                       3rd Qu.:3.75                     
                                       Max.   :4.00                     
                                       NA's   :1                        
     18+               15-44               65+                85+           
 Length:51          Length:51          Length:51          Length:51         
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
     PerPov     
 Min.   : 6.10  
 1st Qu.: 9.05  
 Median :10.80  
 Mean   :11.47  
 3rd Qu.:13.40  
 Max.   :18.90  
                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(USPOP<span class="sc">$</span>Section[<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1  2  3  4 
 9 12 16 13 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(USPOP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "State"   "Total"   "Section" "18-24"   "18+"     "15-44"   "65+"    
[8] "85+"     "PerPov" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>USPOP1<span class="ot">&lt;-</span>   USPOP[,<span class="sc">-</span><span class="dv">1</span>] <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">""</span>, .))))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>USPOP2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(USPOP[,<span class="dv">1</span>],USPOP1)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>USPOP2<span class="sc">$</span>Youth <span class="ot">&lt;-</span> USPOP2[,<span class="dv">4</span>]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(USPOP2<span class="sc">$</span>Youth[<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28206049</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(USPOP2<span class="sc">$</span>Youth[<span class="sc">-</span><span class="dv">1</span>])<span class="sc">==</span>USPOP2<span class="sc">$</span>Youth[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sectionweight <span class="ot">&lt;-</span>  USPOP2[<span class="sc">-</span><span class="dv">1</span>,] <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(Section)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Sample observations from each group</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>stratified_sample1 <span class="ot">&lt;-</span> USPOP2[<span class="sc">-</span><span class="dv">1</span>,] <span class="sc">%&gt;%</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Section) <span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">prop =</span> <span class="fl">0.25</span>)  <span class="co"># Select 25% samples per group</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># View the stratified sample</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>stratified_sample1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 10
# Groups:   Section [4]
   State        Total Section `18-24`  `18+` `15-44`  `65+`  `85+` PerPov  Youth
   &lt;chr&gt;        &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 New Hampsh… 1.28e6       1  114725 9.67e5  549632 1.53e5  19966   6.10 1.15e5
 2 Maine       1.29e6       1  118126 1.02e6  539991 1.86e5  25025  11.9  1.18e5
 3 Illinois    1.26e7       2 1228541 9.35e6 5529191 1.50e6 206861  11.5  1.23e6
 4 Missouri    5.67e6       2  567574 4.28e6 2427133 7.57e5 102956   9.80 5.68e5
 5 Ohio        1.14e7       2 1098431 8.54e6 4811220 1.51e6 190926  10.1  1.10e6
 6 Tennessee   5.80e6       3  553941 4.39e6 2498445 7.19e5  86838  14.5  5.54e5
 7 Alabama     4.49e6       3  452196 3.38e6 1912183 5.89e5  71436  15.2  4.52e5
 8 South Caro… 4.11e6       3  429425 3.13e6 1794151 5.03e5  55259  14.7  4.29e5
 9 Florida     1.67e7       3 1403624 1.28e7 6664700 2.85e6 360332  12.6  1.40e6
10 Utah        2.32e6       4  321169 1.60e6 1102207 1.99e5  24078  10.2  3.21e5
11 Montana     9.09e5       4   92915 6.93e5  371835 1.23e5  16568  13.4  9.29e4
12 Wyoming     4.99e5       4   54248 3.76e5  210398 5.92e4   7273   8.80 5.42e4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(stratified_sample1<span class="sc">$</span>Section)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
1 2 3 4 
2 3 4 3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>strataStat <span class="ot">&lt;-</span> stratified_sample1[,<span class="fu">c</span>(<span class="st">"Section"</span>,<span class="st">"Youth"</span>)] <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Section) <span class="sc">%&gt;%</span>  </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Youth_Section_count =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(Youth)),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Youth_Section_mean =</span> <span class="fu">mean</span>(Youth),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Youth_Section_var =</span> <span class="fu">var</span>(Youth)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>strataStat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  Section Youth_Section_count Youth_Section_mean Youth_Section_var
    &lt;dbl&gt;               &lt;int&gt;              &lt;dbl&gt;             &lt;dbl&gt;
1       1                   2            116426.          5783400.
2       2                   3            964849.     122602523606.
3       3                   4            709796.     216884577416.
4       4                   3            156111.      20806974274.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>sf <span class="ot">&lt;-</span> <span class="fu">table</span>(stratified_sample1<span class="sc">$</span>Section)<span class="sc">/</span><span class="fu">table</span>(USPOP<span class="sc">$</span>Section[<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        1         2         3         4 
0.2222222 0.2500000 0.2500000 0.2307692 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate weighted sum</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>EstTotal <span class="ot">&lt;-</span> <span class="fu">sum</span>(sectionweight<span class="sc">$</span>n<span class="sc">*</span>strataStat<span class="sc">$</span>Youth_Section_mean)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>EstTotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 26012196</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>USPOP2[<span class="dv">1</span>,<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28341732</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>EstVar<span class="ot">&lt;-</span> <span class="fu">sum</span>(sectionweight<span class="sc">$</span>n<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>((<span class="dv">1</span><span class="sc">-</span>sf)<span class="sc">/</span>strataStat<span class="sc">$</span>Youth_Section_count)<span class="sc">*</span>strataStat<span class="sc">$</span>Youth_Section_var)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(EstVar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7931196</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">abs</span>(USPOP2[<span class="dv">1</span>,<span class="dv">4</span>]<span class="sc">-</span>EstTotal)<span class="sc">&lt;</span><span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(EstVar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#5.2 The Florida Survey Research Center has completed a telephone survey on opinions about recycling for a group of cities in Florida. The questionnaire reproduced on the following pages shows the information that was coded to track the city, county, and interviewer, as well as the survey questions asked. The data are stored on the data disk in a file called RECYCLE. The survey used a stratified random sample design with three strata defined by the level of recycling education in the cities: stratum 1 (low education), stratum 2 (moderate education), and stratum 3 (high education). Each response in the dataset includes a stratum code, and the sample sizes were equal across all three strata. The population sizes for the strata are assumed to be nearly equal as well. Your task is to analyze the survey data by selecting two questions of your choice and following these steps: (a) estimate the true population proportion for each selected question; (b) determine whether the proportion of men responding in the category of interest differs from the proportion of women in the same category for each question; (c) for one of the selected questions, estimate the true population proportions within each of the three strata; and (d) for the question used in part (c), compare the true proportions across the three strata to assess whether they differ. To facilitate analysis, you may organize the sampled data in two-way tables for clearer results and calculations. The full survey questionnaire is available in a Word file linked from electronic Section 5.0.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>RECYCLE <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"RECYCLE.XLS"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>Analysisdata <span class="ot">&lt;-</span> RECYCLE[,<span class="fu">c</span>(<span class="st">"Q2a"</span>,<span class="st">"Q3"</span>,<span class="st">"Q24"</span>,<span class="st">"Stratum"</span>)]</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Analysisdata<span class="sc">$</span>Stratum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3 
340 340 340 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>Q2a <span class="ot">&lt;-</span> <span class="fu">table</span>(Analysisdata<span class="sc">$</span>Stratum,Analysisdata<span class="sc">$</span>Q2a)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>Q2a </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      1   2   3
  1 208  52  80
  2 230  48  62
  3 274  28  38</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>PropQ2a <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(Q2a, <span class="at">margin =</span> <span class="dv">1</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>PropQ2a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
             1          2          3
  1 0.61176471 0.15294118 0.23529412
  2 0.67647059 0.14117647 0.18235294
  3 0.80588235 0.08235294 0.11176471</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>(PropQ2a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3 
0.6980392 0.1254902 0.1764706 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>Q3 <span class="ot">&lt;-</span> <span class="fu">table</span>(Analysisdata<span class="sc">$</span>Stratum,Analysisdata<span class="sc">$</span>Q3)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>Q3 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      1   2   3   4   5   6
  1 119   5 102  90  24   0
  2 108  14 116  81  20   1
  3 138   6  92  86  16   2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>PropQ3 <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(Q3, <span class="at">margin =</span> <span class="dv">1</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>PropQ3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
              1           2           3           4           5           6
  1 0.350000000 0.014705882 0.300000000 0.264705882 0.070588235 0.000000000
  2 0.317647059 0.041176471 0.341176471 0.238235294 0.058823529 0.002941176
  3 0.405882353 0.017647059 0.270588235 0.252941176 0.047058824 0.005882353</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>(PropQ3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          1           2           3           4           5           6 
0.357843137 0.024509804 0.303921569 0.251960784 0.058823529 0.002941176 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>Q2aGender <span class="ot">&lt;-</span> <span class="fu">table</span>(Analysisdata<span class="sc">$</span>Q24,Analysisdata<span class="sc">$</span>Q2a)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>Q2aGender </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      1   2   3
  1 260  47  53
  2 452  81 127</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>PropQ2aGender <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(Q2aGender, <span class="at">margin =</span> <span class="dv">1</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>PropQ2aGender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
            1         2         3
  1 0.7222222 0.1305556 0.1472222
  2 0.6848485 0.1227273 0.1924242</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>Q3Gender <span class="ot">&lt;-</span> <span class="fu">table</span>(Analysisdata<span class="sc">$</span>Q24,Analysisdata<span class="sc">$</span>Q3)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>Q3Gender </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      1   2   3   4   5   6
  1 132  11 109  91  16   1
  2 233  14 201 166  44   2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>PropQ3Gender <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(Q3Gender, <span class="at">margin =</span> <span class="dv">1</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>PropQ3Gender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
              1           2           3           4           5           6
  1 0.366666667 0.030555556 0.302777778 0.252777778 0.044444444 0.002777778
  2 0.353030303 0.021212121 0.304545455 0.251515152 0.066666667 0.003030303</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.3 The CARS93 data, in Appendix C, has cars classified as to being one of six different types: small, compact, midsize, large, sporty, or van. A numerical type code is given in the data set, in addition to the actual name of the type. The goal of this activity is to see if poststratification on car type pays any dividends when estimating:</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  Average city gasoline mileage</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportion of cars with air bags</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># for the cars in this population.</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>CARS93 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"CARS93.XLS"</span>)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(CARS93)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   MANUFAC             MODEL               TYPE              MINPRICE    
 Length:92          Length:92          Length:92          Min.   : 6.70  
 Class :character   Class :character   Class :character   1st Qu.:10.88  
 Mode  :character   Mode  :character   Mode  :character   Median :14.70  
                                                          Mean   :17.23  
                                                          3rd Qu.:20.48  
                                                          Max.   :45.40  
                                                                         
    MIDPRICE        MAXPRICE        MPGCITY         MPGHIGH     
 Min.   : 7.40   Min.   : 7.90   Min.   :15.00   Min.   :20.00  
 1st Qu.:12.40   1st Qu.:14.57   1st Qu.:18.00   1st Qu.:26.00  
 Median :17.95   Median :20.30   Median :21.00   Median :28.00  
 Mean   :19.59   Mean   :21.96   Mean   :22.29   Mean   :29.04  
 3rd Qu.:23.40   3rd Qu.:25.55   3rd Qu.:24.25   3rd Qu.:31.00  
 Max.   :61.90   Max.   :80.00   Max.   :46.00   Max.   :50.00  
                                                                
    AIRBAGS          DRIVETR          CYLINDR          LITERS     
 Min.   :0.0000   Min.   :0.0000   Min.   :3.000   Min.   :1.000  
 1st Qu.:0.0000   1st Qu.:1.0000   1st Qu.:4.000   1st Qu.:1.875  
 Median :1.0000   Median :1.0000   Median :4.000   Median :2.400  
 Mean   :0.8152   Mean   :0.9348   Mean   :4.978   Mean   :2.680  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:6.000   3rd Qu.:3.300  
 Max.   :2.0000   Max.   :2.0000   Max.   :8.000   Max.   :5.700  
                                   NA's   :1                      
     HPOWER          RPMMAX          US?            TYPECODE    
 Min.   : 55.0   Min.   :3800   Min.   :0.0000   Min.   :1.000  
 1st Qu.:104.5   1st Qu.:4800   1st Qu.:0.0000   1st Qu.:2.000  
 Median :140.0   Median :5200   Median :1.0000   Median :3.000  
 Mean   :144.4   Mean   :5273   Mean   :0.5109   Mean   :3.109  
 3rd Qu.:170.0   3rd Qu.:5712   3rd Qu.:1.0000   3rd Qu.:4.250  
 Max.   :300.0   Max.   :6500   Max.   :1.0000   Max.   :6.000  
                                                                
      ROW       
 Min.   : 1.00  
 1st Qu.:23.75  
 Median :46.50  
 Mean   :46.50  
 3rd Qu.:69.25  
 Max.   :92.00  
                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Simple random sampling</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>CARS93Sample1 <span class="ot">&lt;-</span> CARS93 <span class="sc">%&gt;%</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">prop =</span> <span class="fl">0.25</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>CARS93Sample1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 17
   MANUFAC   MODEL      TYPE  MINPRICE MIDPRICE MAXPRICE MPGCITY MPGHIGH AIRBAGS
   &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 Chevrolet Corsica    Comp…    11.4     11.4      11.4      25      34       1
 2 Pontiac   Bonneville Large    19.4     24.4      29.4      19      28       2
 3 Ford      Taurus     Mids…    15.6     20.2      24.8      21      30       1
 4 Dodge     Caravan    Van      13.6     19        24.4      17      21       1
 5 Nissan    Quest      Van      16.7     19.1      21.5      17      23       0
 6 Dodge     Colt       Small     7.90     9.20     10.6      29      33       0
 7 Mercury   Capri      Spor…    13.3     14.1      15        23      26       1
 8 Cadillac  DeVille    Large    33       34.7      36.3      16      25       1
 9 Saab      900        Comp…    20.3     28.7      37.1      20      26       1
10 Volvo     240        Comp…    21.8     22.7      23.5      21      28       1
# ℹ 13 more rows
# ℹ 8 more variables: DRIVETR &lt;dbl&gt;, CYLINDR &lt;dbl&gt;, LITERS &lt;dbl&gt;, HPOWER &lt;dbl&gt;,
#   RPMMAX &lt;dbl&gt;, `US?` &lt;dbl&gt;, TYPECODE &lt;dbl&gt;, ROW &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(CARS93Sample1)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(CARS93Sample1<span class="sc">$</span>MPGCITY)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.04348</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(CARS93Sample1<span class="sc">$</span>MPGCITY)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.298275</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>pairbags <span class="ot">&lt;-</span> <span class="fu">sum</span>(CARS93Sample1<span class="sc">$</span>AIRBAGS<span class="sc">&gt;</span><span class="dv">0</span>)<span class="sc">/</span>n</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>pairbags</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7391304</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>varp <span class="ot">&lt;-</span> pairbags<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>pairbags)<span class="sc">/</span>(n<span class="dv">-1</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(varp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1872367</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#poststratification on car type</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">nrow</span>(CARS93)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CARS93<span class="sc">$</span>TYPE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Compact   Large Midsize   Small  Sporty     Van 
     16      11      22      20      14       9 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>SumStratum <span class="ot">&lt;-</span> CARS93 <span class="sc">%&gt;%</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TYPE) <span class="sc">%&gt;%</span>  </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">NStratum =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(TYPE)),</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">WStratum =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(TYPE))<span class="sc">/</span>N</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>SumStratum </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  TYPE    NStratum WStratum
  &lt;chr&gt;      &lt;int&gt;    &lt;dbl&gt;
1 Compact       16   0.174 
2 Large         11   0.120 
3 Midsize       22   0.239 
4 Small         20   0.217 
5 Sporty        14   0.152 
6 Van            9   0.0978</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>SampleSumStratum <span class="ot">&lt;-</span> CARS93Sample1 <span class="sc">%&gt;%</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TYPE) <span class="sc">%&gt;%</span>  </span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">MPGCITY_TYPE_count =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(MPGCITY)),</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">MPGCITY_TYPE_mean =</span> <span class="fu">mean</span>(MPGCITY),</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">MPGCITY_TYPE_var =</span> <span class="fu">var</span>(MPGCITY)</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>SampleSumStratum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  TYPE    MPGCITY_TYPE_count MPGCITY_TYPE_mean MPGCITY_TYPE_var
  &lt;chr&gt;                &lt;int&gt;             &lt;dbl&gt;            &lt;dbl&gt;
1 Compact                  5              22.4            4.3  
2 Large                    4              18.2            2.92 
3 Midsize                  4              19.2            5.58 
4 Small                    4              26.5            9    
5 Sporty                   3              21.3            4.33 
6 Van                      3              17.3            0.333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>sf <span class="ot">&lt;-</span> SampleSumStratum<span class="sc">$</span>MPGCITY_TYPE_count<span class="sc">/</span>SumStratum<span class="sc">$</span>NStratum</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3125000 0.3636364 0.1818182 0.2000000 0.2142857 0.3333333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate weighted sum</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="co">#MPGCITY</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>MPGCITYPostmean <span class="ot">&lt;-</span> <span class="fu">sum</span>(SumStratum<span class="sc">$</span>WStratum<span class="sc">*</span>SampleSumStratum<span class="sc">$</span>MPGCITY_TYPE_mean)</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>MPGCITYPostmean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.38388</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>EstVar<span class="ot">&lt;-</span> <span class="fu">sum</span>(SumStratum<span class="sc">$</span>WStratum<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>((<span class="dv">1</span><span class="sc">-</span>sf)<span class="sc">/</span>SampleSumStratum<span class="sc">$</span>MPGCITY_TYPE_count)<span class="sc">*</span>SampleSumStratum<span class="sc">$</span>MPGCITY_TYPE_var)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(EstVar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.898618</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#AIRBAGS</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>SampleSumStratumAIRBAGS <span class="ot">&lt;-</span> CARS93Sample1 <span class="sc">%&gt;%</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TYPE) <span class="sc">%&gt;%</span>  </span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">AIRBAGS_TYPE_count =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(AIRBAGS)),</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">AIRBAGS_TYPE_prop =</span> <span class="fu">sum</span>(AIRBAGS<span class="sc">&gt;</span><span class="dv">0</span>)<span class="sc">/</span>AIRBAGS_TYPE_count,</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">AIRBAGS_TYPE_var =</span> AIRBAGS_TYPE_prop<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>AIRBAGS_TYPE_prop)</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>SampleSumStratumAIRBAGS</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  TYPE    AIRBAGS_TYPE_count AIRBAGS_TYPE_prop AIRBAGS_TYPE_var
  &lt;chr&gt;                &lt;int&gt;             &lt;dbl&gt;            &lt;dbl&gt;
1 Compact                  5             0.6              0.24 
2 Large                    4             1                0    
3 Midsize                  4             1                0    
4 Small                    4             0.25             0.188
5 Sporty                   3             1                0    
6 Van                      3             0.667            0.222</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate weighted sum</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>AIRBAGSPostProp <span class="ot">&lt;-</span> <span class="fu">sum</span>(SumStratum<span class="sc">$</span>WStratum<span class="sc">*</span>SampleSumStratumAIRBAGS<span class="sc">$</span>AIRBAGS_TYPE_prop)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>AIRBAGSPostProp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7347826</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>EstVar<span class="ot">&lt;-</span> <span class="fu">sum</span>(SumStratum<span class="sc">$</span>WStratum<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>((<span class="dv">1</span><span class="sc">-</span>sf)<span class="sc">/</span>SampleSumStratumAIRBAGS<span class="sc">$</span>AIRBAGS_TYPE_count)<span class="sc">*</span>SampleSumStratumAIRBAGS<span class="sc">$</span>AIRBAGS_TYPE_var)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(EstVar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1138931</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.6</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>HeightProb <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"EXPERIENCE5.6.XLS"</span>)</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(HeightProb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Height       PROB-M            PROB-F             PROB        
 Min.   :56   Min.   :0.00000   Min.   :0.00000   Min.   :0.00025  
 1st Qu.:61   1st Qu.:0.00160   1st Qu.:0.00050   1st Qu.:0.01115  
 Median :66   Median :0.02230   Median :0.02000   Median :0.04390  
 Mean   :66   Mean   :0.04686   Mean   :0.04732   Mean   :0.04709  
 3rd Qu.:71   3rd Qu.:0.08400   3rd Qu.:0.08620   3rd Qu.:0.08070  
 Max.   :76   Max.   :0.14770   Max.   :0.16670   Max.   :0.10530  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>HeightProb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 4
   Height `PROB-M` `PROB-F`     PROB
    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
 1     56  0       0.000500 0.000250
 2     57  0       0.00380  0.00190 
 3     58  0       0.00510  0.00255 
 4     59  0       0.0128   0.00640 
 5     60  0       0.0200   0.0100  
 6     61  0.00180 0.0491   0.0255  
 7     62  0.00160 0.0862   0.0439  
 8     63  0.00270 0.113    0.0579  
 9     64  0.0176  0.127    0.0725  
10     65  0.0148  0.163    0.0888  
# ℹ 11 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>PROBM <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(HeightProb[,<span class="st">"PROB-M"</span>])</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>PROBF <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(HeightProb[,<span class="st">"PROB-F"</span>])</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>PROB <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(HeightProb[,<span class="st">"PROB"</span>])</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>MaleSample <span class="ot">&lt;-</span> <span class="fu">sample</span>(HeightProb<span class="sc">$</span>Height, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> PROBM)</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>MaleSample</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 72 68 73 70 70 71 65 75 69 75 67 67 61 67 67 70 72 72 70 67</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>FemaleSample <span class="ot">&lt;-</span> <span class="fu">sample</span>(HeightProb<span class="sc">$</span>Height, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> PROBF)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>FemaleSample</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 65 66 63 64 64 67 62 67 66 62 60 65 66 68 62 64 65 65 66 57</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">mean</span>(MaleSample)<span class="sc">+</span><span class="fu">mean</span>(FemaleSample))<span class="sc">/</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 66.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">1</span><span class="sc">/</span>n)<span class="sc">*</span>(<span class="fu">var</span>(MaleSample)<span class="sc">+</span><span class="fu">var</span>(FemaleSample))<span class="sc">/</span><span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2315789</code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>AdultSample <span class="ot">&lt;-</span> <span class="fu">sample</span>(HeightProb<span class="sc">$</span>Height, <span class="at">size =</span> <span class="dv">2</span><span class="sc">*</span>n, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> PROB)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>AdultSample</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 71 70 66 69 62 71 62 71 73 65 61 66 65 68 68 67 66 69 73 74 68 61 71 64 63
[26] 63 64 65 64 75 67 63 70 63 73 70 64 74 62 67</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(AdultSample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(AdultSample)<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4053846</code></pre>
</div>
</div>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section">5.1</h3>
<p>Data on the population of the United States is given in Appendix C and on the data disk under USPOP. The goal is to estimate the total U.S. population in the 18–24 age group from a sample of states. The states are divided into four geographic regions. Using these regions as strata, select an appropriately sized stratified random sample of states and use their data on population in the 18- to 24-year-old group to estimate the total U.S. population in that age group. Because the total population is available from the data on all the states, check to see if your estimate is within the margin of error you established for your estimate. Compare your result with those of other students in the class.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sampling)</span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Chap 5: Sampling from Real Populations</span></span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"/Users/luyu/Library/CloudStorage/OneDrive-Xi'anJiaotong-LiverpoolUniversity"</span>)</span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>USPOP <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"USPOP.XLS"</span>)</span>
<span id="cb101-9"><a href="#cb101-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-10"><a href="#cb101-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(USPOP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    State              Total              Section        18-24          
 Length:51          Length:51          Min.   :1.00   Length:51         
 Class :character   Class :character   1st Qu.:2.00   Class :character  
 Mode  :character   Mode  :character   Median :3.00   Mode  :character  
                                       Mean   :2.66                     
                                       3rd Qu.:3.75                     
                                       Max.   :4.00                     
                                       NA's   :1                        
     18+               15-44               65+                85+           
 Length:51          Length:51          Length:51          Length:51         
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
     PerPov     
 Min.   : 6.10  
 1st Qu.: 9.05  
 Median :10.80  
 Mean   :11.47  
 3rd Qu.:13.40  
 Max.   :18.90  
                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(USPOP<span class="sc">$</span>Section[<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1  2  3  4 
 9 12 16 13 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(USPOP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "State"   "Total"   "Section" "18-24"   "18+"     "15-44"   "65+"    
[8] "85+"     "PerPov" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>USPOP1<span class="ot">&lt;-</span>   USPOP[,<span class="sc">-</span><span class="dv">1</span>] <span class="sc">%&gt;%</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">""</span>, .))))</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>USPOP2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(USPOP[,<span class="dv">1</span>],USPOP1)</span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>USPOP2<span class="sc">$</span>Youth <span class="ot">&lt;-</span> USPOP2[,<span class="dv">4</span>]</span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(USPOP2<span class="sc">$</span>Youth[<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28206049</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(USPOP2<span class="sc">$</span>Youth[<span class="sc">-</span><span class="dv">1</span>])<span class="sc">==</span>USPOP2<span class="sc">$</span>Youth[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>sectionweight <span class="ot">&lt;-</span>  USPOP2[<span class="sc">-</span><span class="dv">1</span>,] <span class="sc">%&gt;%</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(Section)</span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Sample observations from each group</span></span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a>stratified_sample1 <span class="ot">&lt;-</span> USPOP2[<span class="sc">-</span><span class="dv">1</span>,] <span class="sc">%&gt;%</span></span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Section) <span class="sc">%&gt;%</span></span>
<span id="cb111-8"><a href="#cb111-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">prop =</span> <span class="fl">0.25</span>)  <span class="co"># Select 25% samples per group</span></span>
<span id="cb111-9"><a href="#cb111-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-10"><a href="#cb111-10" aria-hidden="true" tabindex="-1"></a><span class="co"># View the stratified sample</span></span>
<span id="cb111-11"><a href="#cb111-11" aria-hidden="true" tabindex="-1"></a>stratified_sample1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 10
# Groups:   Section [4]
   State        Total Section `18-24`  `18+` `15-44`  `65+`  `85+` PerPov  Youth
   &lt;chr&gt;        &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 New Hampsh… 1.28e6       1  114725 9.67e5  549632 1.53e5  19966   6.10 1.15e5
 2 Maine       1.29e6       1  118126 1.02e6  539991 1.86e5  25025  11.9  1.18e5
 3 Illinois    1.26e7       2 1228541 9.35e6 5529191 1.50e6 206861  11.5  1.23e6
 4 Missouri    5.67e6       2  567574 4.28e6 2427133 7.57e5 102956   9.80 5.68e5
 5 Ohio        1.14e7       2 1098431 8.54e6 4811220 1.51e6 190926  10.1  1.10e6
 6 Tennessee   5.80e6       3  553941 4.39e6 2498445 7.19e5  86838  14.5  5.54e5
 7 Alabama     4.49e6       3  452196 3.38e6 1912183 5.89e5  71436  15.2  4.52e5
 8 South Caro… 4.11e6       3  429425 3.13e6 1794151 5.03e5  55259  14.7  4.29e5
 9 Florida     1.67e7       3 1403624 1.28e7 6664700 2.85e6 360332  12.6  1.40e6
10 Utah        2.32e6       4  321169 1.60e6 1102207 1.99e5  24078  10.2  3.21e5
11 Montana     9.09e5       4   92915 6.93e5  371835 1.23e5  16568  13.4  9.29e4
12 Wyoming     4.99e5       4   54248 3.76e5  210398 5.92e4   7273   8.80 5.42e4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(stratified_sample1<span class="sc">$</span>Section)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
1 2 3 4 
2 3 4 3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>strataStat <span class="ot">&lt;-</span> stratified_sample1[,<span class="fu">c</span>(<span class="st">"Section"</span>,<span class="st">"Youth"</span>)] <span class="sc">%&gt;%</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Section) <span class="sc">%&gt;%</span>  </span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Youth_Section_count =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(Youth)),</span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Youth_Section_mean =</span> <span class="fu">mean</span>(Youth),</span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Youth_Section_var =</span> <span class="fu">var</span>(Youth)</span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb115-8"><a href="#cb115-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-9"><a href="#cb115-9" aria-hidden="true" tabindex="-1"></a>strataStat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  Section Youth_Section_count Youth_Section_mean Youth_Section_var
    &lt;dbl&gt;               &lt;int&gt;              &lt;dbl&gt;             &lt;dbl&gt;
1       1                   2            116426.          5783400.
2       2                   3            964849.     122602523606.
3       3                   4            709796.     216884577416.
4       4                   3            156111.      20806974274.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>sf <span class="ot">&lt;-</span> <span class="fu">table</span>(stratified_sample1<span class="sc">$</span>Section)<span class="sc">/</span><span class="fu">table</span>(USPOP<span class="sc">$</span>Section[<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        1         2         3         4 
0.2222222 0.2500000 0.2500000 0.2307692 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate weighted sum</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>EstTotal <span class="ot">&lt;-</span> <span class="fu">sum</span>(sectionweight<span class="sc">$</span>n<span class="sc">*</span>strataStat<span class="sc">$</span>Youth_Section_mean)</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>EstTotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 26012196</code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>USPOP2[<span class="dv">1</span>,<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28341732</code></pre>
</div>
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>EstVar<span class="ot">&lt;-</span> <span class="fu">sum</span>(sectionweight<span class="sc">$</span>n<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>((<span class="dv">1</span><span class="sc">-</span>sf)<span class="sc">/</span>strataStat<span class="sc">$</span>Youth_Section_count)<span class="sc">*</span>strataStat<span class="sc">$</span>Youth_Section_var)</span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(EstVar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7931196</code></pre>
</div>
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">abs</span>(USPOP2[<span class="dv">1</span>,<span class="dv">4</span>]<span class="sc">-</span>EstTotal)<span class="sc">&lt;</span><span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(EstVar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="section-1" class="level3">
<h3 class="anchored" data-anchor-id="section-1">5.2</h3>
<p>The Florida Survey Research Center has completed a telephone survey on opinions about recycling for a group of cities in Florida. The questionnaire reproduced on the following pages shows the information that was coded to track the city, county, and interviewer, as well as the survey questions asked. The data are stored on the data disk in a file called RECYCLE. The survey used a stratified random sample design with three strata defined by the level of recycling education in the cities: stratum 1 (low education), stratum 2 (moderate education), and stratum 3 (high education). Each response in the dataset includes a stratum code, and the sample sizes were equal across all three strata. The population sizes for the strata are assumed to be nearly equal as well. Your task is to analyze the survey data by selecting two questions of your choice and following these steps:</p>
<ol type="a">
<li>estimate the true population proportion for each selected question; (b) determine whether the proportion of men responding in the category of interest differs from the proportion of women in the same category for each question;</li>
<li>for one of the selected questions, estimate the true population proportions within each of the three strata; and (d) for the question used in part (c), compare the true proportions across the three strata to assess whether they differ.</li>
</ol>
<p>To facilitate analysis, you may organize the sampled data in two-way tables for clearer results and calculations. The full survey questionnaire is available in a Word file linked from electronic Section 5.0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"/Users/luyu/Library/CloudStorage/OneDrive-Xi'anJiaotong-LiverpoolUniversity"</span>)</span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>RECYCLE <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"RECYCLE.XLS"</span>)</span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a>Analysisdata <span class="ot">&lt;-</span> RECYCLE[,<span class="fu">c</span>(<span class="st">"Q2a"</span>,<span class="st">"Q3"</span>,<span class="st">"Q24"</span>,<span class="st">"Stratum"</span>)]</span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Analysisdata<span class="sc">$</span>Stratum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3 
340 340 340 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>Q2a <span class="ot">&lt;-</span> <span class="fu">table</span>(Analysisdata<span class="sc">$</span>Stratum,Analysisdata<span class="sc">$</span>Q2a)</span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>Q2a </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      1   2   3
  1 208  52  80
  2 230  48  62
  3 274  28  38</code></pre>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>PropQ2a <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(Q2a, <span class="at">margin =</span> <span class="dv">1</span>)</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>PropQ2a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
             1          2          3
  1 0.61176471 0.15294118 0.23529412
  2 0.67647059 0.14117647 0.18235294
  3 0.80588235 0.08235294 0.11176471</code></pre>
</div>
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>(PropQ2a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3 
0.6980392 0.1254902 0.1764706 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>Q3 <span class="ot">&lt;-</span> <span class="fu">table</span>(Analysisdata<span class="sc">$</span>Stratum,Analysisdata<span class="sc">$</span>Q3)</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a>Q3 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      1   2   3   4   5   6
  1 119   5 102  90  24   0
  2 108  14 116  81  20   1
  3 138   6  92  86  16   2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>PropQ3 <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(Q3, <span class="at">margin =</span> <span class="dv">1</span>)</span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a>PropQ3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
              1           2           3           4           5           6
  1 0.350000000 0.014705882 0.300000000 0.264705882 0.070588235 0.000000000
  2 0.317647059 0.041176471 0.341176471 0.238235294 0.058823529 0.002941176
  3 0.405882353 0.017647059 0.270588235 0.252941176 0.047058824 0.005882353</code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>(PropQ3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          1           2           3           4           5           6 
0.357843137 0.024509804 0.303921569 0.251960784 0.058823529 0.002941176 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>Q2aGender <span class="ot">&lt;-</span> <span class="fu">table</span>(Analysisdata<span class="sc">$</span>Q24,Analysisdata<span class="sc">$</span>Q2a)</span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>Q2aGender </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      1   2   3
  1 260  47  53
  2 452  81 127</code></pre>
</div>
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>PropQ2aGender <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(Q2aGender, <span class="at">margin =</span> <span class="dv">1</span>)</span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a>PropQ2aGender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
            1         2         3
  1 0.7222222 0.1305556 0.1472222
  2 0.6848485 0.1227273 0.1924242</code></pre>
</div>
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a>Q3Gender <span class="ot">&lt;-</span> <span class="fu">table</span>(Analysisdata<span class="sc">$</span>Q24,Analysisdata<span class="sc">$</span>Q3)</span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>Q3Gender </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      1   2   3   4   5   6
  1 132  11 109  91  16   1
  2 233  14 201 166  44   2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>PropQ3Gender <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(Q3Gender, <span class="at">margin =</span> <span class="dv">1</span>)</span>
<span id="cb147-2"><a href="#cb147-2" aria-hidden="true" tabindex="-1"></a>PropQ3Gender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
              1           2           3           4           5           6
  1 0.366666667 0.030555556 0.302777778 0.252777778 0.044444444 0.002777778
  2 0.353030303 0.021212121 0.304545455 0.251515152 0.066666667 0.003030303</code></pre>
</div>
</div>
</section>
<section id="section-2" class="level3">
<h3 class="anchored" data-anchor-id="section-2">5.3</h3>
<p>The CARS93 data, in Appendix C, has cars classified as to being one of six different types: small, compact, midsize, large, sporty, or van. A numerical type code is given in the data set, in addition to the actual name of the type. The goal of this activity is to see if poststratification on car type pays any dividends when estimating:</p>
<p>Average city gasoline mileage</p>
<p>Proportion of cars with air bags</p>
<p>for the cars in this population</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"/Users/luyu/Library/CloudStorage/OneDrive-Xi'anJiaotong-LiverpoolUniversity"</span>)</span>
<span id="cb149-2"><a href="#cb149-2" aria-hidden="true" tabindex="-1"></a>CARS93 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"CARS93.XLS"</span>)</span>
<span id="cb149-3"><a href="#cb149-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(CARS93)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   MANUFAC             MODEL               TYPE              MINPRICE    
 Length:92          Length:92          Length:92          Min.   : 6.70  
 Class :character   Class :character   Class :character   1st Qu.:10.88  
 Mode  :character   Mode  :character   Mode  :character   Median :14.70  
                                                          Mean   :17.23  
                                                          3rd Qu.:20.48  
                                                          Max.   :45.40  
                                                                         
    MIDPRICE        MAXPRICE        MPGCITY         MPGHIGH     
 Min.   : 7.40   Min.   : 7.90   Min.   :15.00   Min.   :20.00  
 1st Qu.:12.40   1st Qu.:14.57   1st Qu.:18.00   1st Qu.:26.00  
 Median :17.95   Median :20.30   Median :21.00   Median :28.00  
 Mean   :19.59   Mean   :21.96   Mean   :22.29   Mean   :29.04  
 3rd Qu.:23.40   3rd Qu.:25.55   3rd Qu.:24.25   3rd Qu.:31.00  
 Max.   :61.90   Max.   :80.00   Max.   :46.00   Max.   :50.00  
                                                                
    AIRBAGS          DRIVETR          CYLINDR          LITERS     
 Min.   :0.0000   Min.   :0.0000   Min.   :3.000   Min.   :1.000  
 1st Qu.:0.0000   1st Qu.:1.0000   1st Qu.:4.000   1st Qu.:1.875  
 Median :1.0000   Median :1.0000   Median :4.000   Median :2.400  
 Mean   :0.8152   Mean   :0.9348   Mean   :4.978   Mean   :2.680  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:6.000   3rd Qu.:3.300  
 Max.   :2.0000   Max.   :2.0000   Max.   :8.000   Max.   :5.700  
                                   NA's   :1                      
     HPOWER          RPMMAX          US?            TYPECODE    
 Min.   : 55.0   Min.   :3800   Min.   :0.0000   Min.   :1.000  
 1st Qu.:104.5   1st Qu.:4800   1st Qu.:0.0000   1st Qu.:2.000  
 Median :140.0   Median :5200   Median :1.0000   Median :3.000  
 Mean   :144.4   Mean   :5273   Mean   :0.5109   Mean   :3.109  
 3rd Qu.:170.0   3rd Qu.:5712   3rd Qu.:1.0000   3rd Qu.:4.250  
 Max.   :300.0   Max.   :6500   Max.   :1.0000   Max.   :6.000  
                                                                
      ROW       
 Min.   : 1.00  
 1st Qu.:23.75  
 Median :46.50  
 Mean   :46.50  
 3rd Qu.:69.25  
 Max.   :92.00  
                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Simple random sampling</span></span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb151-3"><a href="#cb151-3" aria-hidden="true" tabindex="-1"></a>CARS93Sample1 <span class="ot">&lt;-</span> CARS93 <span class="sc">%&gt;%</span></span>
<span id="cb151-4"><a href="#cb151-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">prop =</span> <span class="fl">0.25</span>)</span>
<span id="cb151-5"><a href="#cb151-5" aria-hidden="true" tabindex="-1"></a>CARS93Sample1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 17
   MANUFAC   MODEL      TYPE  MINPRICE MIDPRICE MAXPRICE MPGCITY MPGHIGH AIRBAGS
   &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 Chevrolet Corsica    Comp…    11.4     11.4      11.4      25      34       1
 2 Pontiac   Bonneville Large    19.4     24.4      29.4      19      28       2
 3 Ford      Taurus     Mids…    15.6     20.2      24.8      21      30       1
 4 Dodge     Caravan    Van      13.6     19        24.4      17      21       1
 5 Nissan    Quest      Van      16.7     19.1      21.5      17      23       0
 6 Dodge     Colt       Small     7.90     9.20     10.6      29      33       0
 7 Mercury   Capri      Spor…    13.3     14.1      15        23      26       1
 8 Cadillac  DeVille    Large    33       34.7      36.3      16      25       1
 9 Saab      900        Comp…    20.3     28.7      37.1      20      26       1
10 Volvo     240        Comp…    21.8     22.7      23.5      21      28       1
# ℹ 13 more rows
# ℹ 8 more variables: DRIVETR &lt;dbl&gt;, CYLINDR &lt;dbl&gt;, LITERS &lt;dbl&gt;, HPOWER &lt;dbl&gt;,
#   RPMMAX &lt;dbl&gt;, `US?` &lt;dbl&gt;, TYPECODE &lt;dbl&gt;, ROW &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(CARS93Sample1)</span>
<span id="cb153-2"><a href="#cb153-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb153-3"><a href="#cb153-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(CARS93Sample1<span class="sc">$</span>MPGCITY)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.04348</code></pre>
</div>
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(CARS93Sample1<span class="sc">$</span>MPGCITY)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.298275</code></pre>
</div>
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a>pairbags <span class="ot">&lt;-</span> <span class="fu">sum</span>(CARS93Sample1<span class="sc">$</span>AIRBAGS<span class="sc">&gt;</span><span class="dv">0</span>)<span class="sc">/</span>n</span>
<span id="cb157-2"><a href="#cb157-2" aria-hidden="true" tabindex="-1"></a>pairbags</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7391304</code></pre>
</div>
<div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a>varp <span class="ot">&lt;-</span> pairbags<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>pairbags)<span class="sc">/</span>(n<span class="dv">-1</span>)</span>
<span id="cb159-2"><a href="#cb159-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(varp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1872367</code></pre>
</div>
<div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="co">#poststratification on car type</span></span>
<span id="cb161-2"><a href="#cb161-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">nrow</span>(CARS93)</span>
<span id="cb161-3"><a href="#cb161-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(CARS93<span class="sc">$</span>TYPE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Compact   Large Midsize   Small  Sporty     Van 
     16      11      22      20      14       9 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb163"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb163-1"><a href="#cb163-1" aria-hidden="true" tabindex="-1"></a>SumStratum <span class="ot">&lt;-</span> CARS93 <span class="sc">%&gt;%</span></span>
<span id="cb163-2"><a href="#cb163-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TYPE) <span class="sc">%&gt;%</span>  </span>
<span id="cb163-3"><a href="#cb163-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb163-4"><a href="#cb163-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">NStratum =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(TYPE)),</span>
<span id="cb163-5"><a href="#cb163-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">WStratum =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(TYPE))<span class="sc">/</span>N</span>
<span id="cb163-6"><a href="#cb163-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb163-7"><a href="#cb163-7" aria-hidden="true" tabindex="-1"></a>SumStratum </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  TYPE    NStratum WStratum
  &lt;chr&gt;      &lt;int&gt;    &lt;dbl&gt;
1 Compact       16   0.174 
2 Large         11   0.120 
3 Midsize       22   0.239 
4 Small         20   0.217 
5 Sporty        14   0.152 
6 Van            9   0.0978</code></pre>
</div>
<div class="sourceCode cell-code" id="cb165"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb165-1"><a href="#cb165-1" aria-hidden="true" tabindex="-1"></a>SampleSumStratum <span class="ot">&lt;-</span> CARS93Sample1 <span class="sc">%&gt;%</span></span>
<span id="cb165-2"><a href="#cb165-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TYPE) <span class="sc">%&gt;%</span>  </span>
<span id="cb165-3"><a href="#cb165-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb165-4"><a href="#cb165-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">MPGCITY_TYPE_count =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(MPGCITY)),</span>
<span id="cb165-5"><a href="#cb165-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">MPGCITY_TYPE_mean =</span> <span class="fu">mean</span>(MPGCITY),</span>
<span id="cb165-6"><a href="#cb165-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">MPGCITY_TYPE_var =</span> <span class="fu">var</span>(MPGCITY)</span>
<span id="cb165-7"><a href="#cb165-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb165-8"><a href="#cb165-8" aria-hidden="true" tabindex="-1"></a>SampleSumStratum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  TYPE    MPGCITY_TYPE_count MPGCITY_TYPE_mean MPGCITY_TYPE_var
  &lt;chr&gt;                &lt;int&gt;             &lt;dbl&gt;            &lt;dbl&gt;
1 Compact                  5              22.4            4.3  
2 Large                    4              18.2            2.92 
3 Midsize                  4              19.2            5.58 
4 Small                    4              26.5            9    
5 Sporty                   3              21.3            4.33 
6 Van                      3              17.3            0.333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb167"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb167-1"><a href="#cb167-1" aria-hidden="true" tabindex="-1"></a>sf <span class="ot">&lt;-</span> SampleSumStratum<span class="sc">$</span>MPGCITY_TYPE_count<span class="sc">/</span>SumStratum<span class="sc">$</span>NStratum</span>
<span id="cb167-2"><a href="#cb167-2" aria-hidden="true" tabindex="-1"></a>sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3125000 0.3636364 0.1818182 0.2000000 0.2142857 0.3333333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb169"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb169-1"><a href="#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate weighted sum</span></span>
<span id="cb169-2"><a href="#cb169-2" aria-hidden="true" tabindex="-1"></a><span class="co">#MPGCITY</span></span>
<span id="cb169-3"><a href="#cb169-3" aria-hidden="true" tabindex="-1"></a>MPGCITYPostmean <span class="ot">&lt;-</span> <span class="fu">sum</span>(SumStratum<span class="sc">$</span>WStratum<span class="sc">*</span>SampleSumStratum<span class="sc">$</span>MPGCITY_TYPE_mean)</span>
<span id="cb169-4"><a href="#cb169-4" aria-hidden="true" tabindex="-1"></a>MPGCITYPostmean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.38388</code></pre>
</div>
<div class="sourceCode cell-code" id="cb171"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb171-1"><a href="#cb171-1" aria-hidden="true" tabindex="-1"></a>EstVar<span class="ot">&lt;-</span> <span class="fu">sum</span>(SumStratum<span class="sc">$</span>WStratum<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>((<span class="dv">1</span><span class="sc">-</span>sf)<span class="sc">/</span>SampleSumStratum<span class="sc">$</span>MPGCITY_TYPE_count)<span class="sc">*</span>SampleSumStratum<span class="sc">$</span>MPGCITY_TYPE_var)</span>
<span id="cb171-2"><a href="#cb171-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(EstVar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.898618</code></pre>
</div>
<div class="sourceCode cell-code" id="cb173"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb173-1"><a href="#cb173-1" aria-hidden="true" tabindex="-1"></a><span class="co">#AIRBAGS</span></span>
<span id="cb173-2"><a href="#cb173-2" aria-hidden="true" tabindex="-1"></a>SampleSumStratumAIRBAGS <span class="ot">&lt;-</span> CARS93Sample1 <span class="sc">%&gt;%</span></span>
<span id="cb173-3"><a href="#cb173-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TYPE) <span class="sc">%&gt;%</span>  </span>
<span id="cb173-4"><a href="#cb173-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb173-5"><a href="#cb173-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">AIRBAGS_TYPE_count =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(AIRBAGS)),</span>
<span id="cb173-6"><a href="#cb173-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">AIRBAGS_TYPE_prop =</span> <span class="fu">sum</span>(AIRBAGS<span class="sc">&gt;</span><span class="dv">0</span>)<span class="sc">/</span>AIRBAGS_TYPE_count,</span>
<span id="cb173-7"><a href="#cb173-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">AIRBAGS_TYPE_var =</span> AIRBAGS_TYPE_prop<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>AIRBAGS_TYPE_prop)</span>
<span id="cb173-8"><a href="#cb173-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb173-9"><a href="#cb173-9" aria-hidden="true" tabindex="-1"></a>SampleSumStratumAIRBAGS</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  TYPE    AIRBAGS_TYPE_count AIRBAGS_TYPE_prop AIRBAGS_TYPE_var
  &lt;chr&gt;                &lt;int&gt;             &lt;dbl&gt;            &lt;dbl&gt;
1 Compact                  5             0.6              0.24 
2 Large                    4             1                0    
3 Midsize                  4             1                0    
4 Small                    4             0.25             0.188
5 Sporty                   3             1                0    
6 Van                      3             0.667            0.222</code></pre>
</div>
<div class="sourceCode cell-code" id="cb175"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb175-1"><a href="#cb175-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate weighted sum</span></span>
<span id="cb175-2"><a href="#cb175-2" aria-hidden="true" tabindex="-1"></a>AIRBAGSPostProp <span class="ot">&lt;-</span> <span class="fu">sum</span>(SumStratum<span class="sc">$</span>WStratum<span class="sc">*</span>SampleSumStratumAIRBAGS<span class="sc">$</span>AIRBAGS_TYPE_prop)</span>
<span id="cb175-3"><a href="#cb175-3" aria-hidden="true" tabindex="-1"></a>AIRBAGSPostProp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7347826</code></pre>
</div>
<div class="sourceCode cell-code" id="cb177"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb177-1"><a href="#cb177-1" aria-hidden="true" tabindex="-1"></a>EstVar<span class="ot">&lt;-</span> <span class="fu">sum</span>(SumStratum<span class="sc">$</span>WStratum<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>((<span class="dv">1</span><span class="sc">-</span>sf)<span class="sc">/</span>SampleSumStratumAIRBAGS<span class="sc">$</span>AIRBAGS_TYPE_count)<span class="sc">*</span>SampleSumStratumAIRBAGS<span class="sc">$</span>AIRBAGS_TYPE_var)</span>
<span id="cb177-2"><a href="#cb177-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">sqrt</span>(EstVar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1138931</code></pre>
</div>
</div>
</section>
<section id="section-3" class="level3">
<h3 class="anchored" data-anchor-id="section-3">5.6</h3>
<p>We now move from selecting samples from real sets of data to selecting samples from probability distributions. The probability distributions partially given in the following table represent the heights of adults in America. The complete set of data is available via a link from electronic Section 5.0. PROB-M denotes the probabilities of various heights (in inches) for males, PROB-F denotes the probabilities for females, and PROB denotes the combined probabilities for adults. The goal is to:</p>
<p>Select samples from these distributions</p>
<p>Compare estimates of the average height from:</p>
<p>Stratified random sampling</p>
<p>Simple random sampling</p>
<p></p>
</section>
</section>
</section>
<section id="central-limit-theorem" class="level1">
<h1>Central Limit Theorem</h1>
<p><span class="math inline">\(X_1, X_2,..., X_n \sim^{iid} F(\mu, \sigma^2)\)</span>, <span class="math inline">\(Y_n=\sqrt n \frac{\bar x- \mu}{\sigma} --&gt;N(0,1)\)</span></p>
<p>(p.s. Apart from this, CLT also says that When the sample size is large enough (n <span class="math inline">\(\geq\)</span> 30), the mean distribution of the sample is normal. But here we just prove the above thing)</p>
<p>Proof: (based on MGF)</p>
<p><span class="math inline">\(z_i =(x_i-\mu)/ \sigma\)</span> where <span class="math inline">\(Y_n=\sqrt n \bar z\)</span> and <span class="math inline">\(z_i \sim ^{iid} F(0,1)\)</span></p>
<p><span class="math display">\[
E(e^{tZ}) = m(t) \implies
\begin{cases}
m(0) = 1 \\
m'(0) = 0 = E(Z) \\
m''(0) = 1 + 0^2 = 1 = E(Z^2)
\end{cases}
\]</span></p>
<p><span class="math display">\[m(t) = m(0) + m'(0)t + \frac{m''(\xi)}{2}t^2, \quad 0 &lt; \xi &lt; t\]</span></p>
<p><span class="math display">\[M_{Y_n}(t) = E\left[ \exp\left\{ t \sum_{i=1}^n \frac{Z_i}{\sqrt{n}} \right\} \right] = \prod_{i=1}^n E\left[ \exp\left\{ \frac{t Z_i}{\sqrt{n}} \right\} \right].\]</span></p>
<p><span class="math display">\[= \left[ m\left( \frac{t}{\sqrt{n}} \right) \right]^n = \left[ 1 + \frac{m''(\xi) t^2}{2n} \right]^n, \quad 0 &lt; \xi &lt; \frac{t}{\sqrt{n}}.\]</span></p>
<p><span class="math inline">\(n \to \infty, \quad \frac{t}{\sqrt{n}} \to 0 \implies \xi \to 0 \implies m''(\xi) \to m''(0) = 1.\)</span></p>
<p><span class="math inline">\(M_{Y_n}(t) \to \left[ 1 + \frac{t^2}{2n} \right]^n \to e^{\frac{t^2}{2}} = E(e^{tZ})\)</span></p>
<p><span class="math inline">\(\left[ 1 + \frac{t}{n} \right]^n \to e^t \quad \text{Y}_n \xrightarrow{d} N(0,1)\)</span></p>
<p><span class="math inline">\(\textbf{Hajek}\)</span> Let <span class="math inline">\(m_N = \max_{1 \leq i \leq n} (y_i - \bar{y})\)</span>. Then if</p>
<p><span class="math inline">\(\frac{1}{\min(n, N-n)} \frac{m_N}{S_y^2} \to 0, \quad \frac{\bar{y} - Y}{\sqrt{\text{Var}(\bar y)}} \xrightarrow{d} N(0,1)\)</span></p>
<section id="limit-distribution" class="level2">
<h2 class="anchored" data-anchor-id="limit-distribution">Limit Distribution</h2>
<p>Wold-weorwilz Thm</p>
<p><span class="math inline">\(\{a_{N_1}, \ldots, a_{N_n}\}\)</span>, <span class="math inline">\(\{X_{n_1}, \ldots, X_{n_N}\}\)</span>,</p>
<p><span class="math display">\[
\frac{\frac{1}{N} \sum (a_{N_i} - \overline{a_N})^r}{\left[ \frac{1}{N} \sum (a_{N_i} - \overline{a_N})^2 \right]^{r/2}} = O(1), \quad \overline{a_N} = \frac{1}{N} \sum a_{N_i}.
\]</span></p>
<p><span class="math display">\[
\frac{\frac{1}{N} \sum (X_{N_i} - \overline{X_N})^r}{\left[ \frac{1}{N} \sum (X_{N_i} - \overline{X_N})^2 \right]^{r/2}} = O(1) \quad X_N = \frac{1}{N} \sum X_{N_i}.
\]</span> <span class="math inline">\(X_1,X_2,...X_N\)</span> uniformly distributio from <span class="math inline">\(X_{N_1},...\)</span></p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Let <span class="math inline">\(X_1, X_2, \ldots, X_n\)</span> i.i.d. <span class="math inline">\(F(\mu, \sigma^2)\)</span>. Define <span class="math inline">\(Y_n = \sqrt{n} \frac{\overline{X} - \mu}{\sigma} \xrightarrow{d} N(0,1)\)</span>.</p>
<p>Let <span class="math inline">\(L_N = \sum a_{N_i} X_i\)</span>, <span class="math inline">\(E[L_N] = N \overline{a_N} \overline{X}\)</span>.</p>
<p><span class="math display">\[
\text{Var}(L_N) = \frac{1}{N-1} \left[ \sum (a_{N_i} - \overline{a_N})^2 \right] \left[ \sum (X_{N_i} - \overline{X})^2 \right]
\]</span></p>
<p>As <span class="math inline">\(N \to \infty\)</span>,</p>
<p><span class="math display">\[
P\left\{ \frac{L_N - E(L_N)}{\sqrt{\text{Var}(L_N)}} \leq z \right\} \to \frac{1}{\sqrt{2\pi}} \int_{-\infty}^z e^{-\frac{t^2}{2}} dt.
\]</span></p>
<section id="this-leads-the-construction-of-confidence-interval-as-well-as-sample-size-which-is-one-of-keys-to-survey-sampling" class="level3">
<h3 class="anchored" data-anchor-id="this-leads-the-construction-of-confidence-interval-as-well-as-sample-size-which-is-one-of-keys-to-survey-sampling">This leads the construction of confidence interval as well as sample size, which is one of keys to SURVEY SAMPLING</h3>
</section>
</section>
</section>
<section id="basic-knowledge-of-statistics" class="level1">
<h1>Basic knowledge of Statistics</h1>
<section id="sampling-distribution" class="level2">
<h2 class="anchored" data-anchor-id="sampling-distribution">Sampling distribution</h2>
<p>What we learned before about sampling distribution are the situation of “Sampling with Replacement”.</p>
<p>We are beginning to embark a journey that allows us to learn about populations by obtaining data from samples since it is rare that we know all values in an entire population.</p>
<p><strong>Sampling distribution of a statistic</strong> is the probability distribution of a sample statistics (such as mean/proportion which tend to target the population mean/proportion), with all samples having the same sample size. This concept is important to understand. The behavior of a statistic can be known by understanding its distribution( (The random variable in this case is the value of that sample statistics)). Under certain condition, the distribution of sampling mean/proportion approximates a normal distribution.</p>
<p><strong>Though statistics does not depend on unknown parameters, the distribution of it depend on unknown parameters.(eg. Normal distribution of sample means depends on population mean(an unknow parameter) and standard deviation)</strong></p>
<p>(ps: the advantage of sampling with replacement:</p>
<p>when selecting a relatively small sample from a large population, it makes no significant difference whether we sample with or without replacement.</p>
<p>Sampling with replacement results in independent events that are unaffected by previous outcomes, and independent events are easier to analyze and they result in simpler formulas.)</p>
<p><strong>For a fixed sample size, the mean of all possible sample means is equal to the mean of population though sample means vary(sampling variability)</strong></p>
<section id="example" class="level3">
<h3 class="anchored" data-anchor-id="example">Example</h3>
<p>If the population follows <span class="math inline">\(N \sim (\mu, \sigma^2)\)</span>, the sampling distribution of mean follows <span class="math inline">\(N \sim (\mu, \sigma^2/\sqrt n)\)</span></p>
</section>
</section>
</section>
<section id="basic-knowledge-in-survey-sampling" class="level1">
<h1>Basic knowledge in Survey sampling</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 73%">
</colgroup>
<thead>
<tr class="header">
<th>Elementary Unit</th>
<th>In sampling we get information from an individual, which is called an individual unit.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Population</td>
<td>The sum of all individual units in a given investigation at a given time.</td>
</tr>
<tr class="even">
<td>—————–</td>
<td>————————————————————————————————</td>
</tr>
<tr class="odd">
<td>Sample</td>
<td>A subset of the Population</td>
</tr>
<tr class="even">
<td>—————–</td>
<td>————————————————————————————————</td>
</tr>
<tr class="odd">
<td>Subpopulation</td>
<td>A specific part of the Population of the study. Typically, subgroups and study domains are not the same.</td>
</tr>
<tr class="even">
<td>—————–</td>
<td>————————————————————————————————</td>
</tr>
<tr class="odd">
<td>Enumeration Unit and Sampling Unit</td>
<td>Individuals that would be selected under a particular sampling mechanism.</td>
</tr>
<tr class="even">
<td>—————–</td>
<td>————————————————————————————————</td>
</tr>
</tbody>
</table>
</section>
<section id="chapter-4-simple-random-sampling-srs" class="level1">
<h1>Chapter 4 Simple Random Sampling (SRS)</h1>
<section id="estimator-for-population-mean" class="level2">
<h2 class="anchored" data-anchor-id="estimator-for-population-mean">Estimator for population mean</h2>
<p>Estimator for population mean <span class="math inline">\(\mu\)</span>: <span class="math display">\[
\hat{\mu} = \bar{y} =  \frac{1}{n}\sum_{i=1}^n y_i
\]</span></p>
<p>Estimator for the variance of <span class="math inline">\(\bar{y}\)</span> <span class="math display">\[
\hat{V}(\bar{y}) = \left( 1-\frac{n}{N} \right) \frac{s^2}{n}
\]</span></p>
</section>
<section id="estimator-for-population-total" class="level2">
<h2 class="anchored" data-anchor-id="estimator-for-population-total">Estimator for population total</h2>
<p>Estimator for population total <span class="math inline">\(\hat{\tau}\)</span>: <span class="math display">\[
\hat{\tau} = N\bar{y} =  \frac{N}{n}\sum_{i=1}^n y_i
\]</span></p>
<p>Estimator for the variance of <span class="math inline">\(\tau\)</span> <span class="math display">\[
\hat{V}(\hat{\tau}) = \hat{V}(N\bar{y}) = N^2 \left( 1-\frac{n}{N} \right) \frac{s^2}{n}
\]</span></p>
<section id="a-note-on-bounds" class="level3">
<h3 class="anchored" data-anchor-id="a-note-on-bounds">A note on Bounds</h3>
<p>The estimator for the bound on the error of estimation is <span class="math inline">\(2\sqrt{V(\hat\lambda)}\)</span> where <span class="math inline">\(V(\hat\lambda)\)</span> is the variance of the estimator (<span class="math inline">\(\hat\mu\)</span>, <span class="math inline">\(\hat\tau\)</span>, or <span class="math inline">\(\hat{p}\)</span>).<br>
<em>(Notation deviates from the textbook)</em><br>
<span class="math inline">\(2\)</span> is an approximated version of a t-test of 1.96 (95% CI of two sides) that the text uses to simplify calculation.</p>
</section>
</section>
<section id="sample-size-estimates-for-population-mean-and-for-population-total" class="level2">
<h2 class="anchored" data-anchor-id="sample-size-estimates-for-population-mean-and-for-population-total">Sample size estimates for population mean and for population total</h2>
<p>Sample size required to estimate <span class="math inline">\(\mu\)</span> or <span class="math inline">\(\tau\)</span> with a bound on the error of estimation <span class="math inline">\(B\)</span>. <span class="math display">\[
n = \frac{N\sigma^2}{(N-1)D + \sigma^2} \\
\text{where} \\
D = \frac{B^2}{4} \text{ for } \mu \text{ and} \\
D = \frac{B^2}{4N^2} \text{ for } \tau
\]</span></p>
<section id="fuction-in-r-for-sample-size-estimate" class="level3">
<h3 class="anchored" data-anchor-id="fuction-in-r-for-sample-size-estimate">Fuction in R for sample size estimate</h3>
</section>
</section>
<section id="estimator-for-population-proportion" class="level2">
<h2 class="anchored" data-anchor-id="estimator-for-population-proportion">Estimator for population proportion</h2>
<p>Estimator for the population proportion <span class="math inline">\(p\)</span>: <span class="math display">\[
\hat{p} = \bar{y} = \frac{\sum_{i=1}^n y_i}{n}
\]</span></p>
<p>Estimated variance of <span class="math inline">\(\hat{p}\)</span>: <span class="math display">\[
\hat{V}(\hat{p}) = \left(1 - \frac{n}{N} \right) \frac{\hat{p} \hat{q}}{n-1} \\
\text{where} \\
\hat{q} = 1-\hat{p}
\]</span></p>
</section>
<section id="sample-size-estimate-for-population-proportion" class="level2">
<h2 class="anchored" data-anchor-id="sample-size-estimate-for-population-proportion">Sample size estimate for population proportion</h2>
<p><span class="math inline">\(\sigma^2\)</span> si replaced with <span class="math inline">\(pq\)</span> in the sample size formula to estimate <span class="math inline">\(p\)</span> with a bound on the error of estimation <span class="math inline">\(B\)</span>: <span class="math display">\[
n = \frac{Npq}{(N-1)D + pq} \\
\text{where} \\
D = \frac{B^2}{4}
\]</span></p>
</section>
<section id="example-exercise" class="level2">
<h2 class="anchored" data-anchor-id="example-exercise">Example Exercise</h2>
<ol type="1">
<li>The Fish and Game Department of a particular state was concerned about the direction of its future hunting programs. To provide for a greater potential for future hunting, the department wanted to determine the proportion of hunters seeking any type of game bird. A simple random sample of <span class="math inline">\(n=1000\)</span> of the <span class="math inline">\(N=99,000\)</span> licensed hunters was obtained. Suppose 430 indicated that they hunted game birds. Estimate <span class="math inline">\(p\)</span>, the proportion of licensed hunters seeking game birds. Place a bound on the error of estimation. Using the data, determine the sample size the department must obtain to estimate the proportion of game bird hunters, given a bound on the error of estimation of magnitude <span class="math inline">\(B=0.02\)</span>. Recall the estimator of a simple random sample. The proportion <span class="math inline">\(\hat{p}=\frac{1}{n} \sum_{i=1}^n y_i=\frac{430}{1000}=\frac{43}{100}\)</span> The bound on the error of <span class="math inline">\(\hat{p}\)</span> is <span class="math display">\[
\begin{aligned}
2 \sqrt{\hat{v}(\hat{p})} &amp; =2 \sqrt{\left(1-\frac{1000}{99000}\right) \times \frac{\frac{43}{100} \times\left(1-\frac{43}{1000}\right)}{1000-1}} \\
&amp; =2 \times \sqrt{\frac{98}{99} \times \frac{43}{100} \times \frac{57}{100} \times \frac{1}{998}} \\
&amp; =2 \times 0.016 \\
&amp; =0.032
\end{aligned}
\]</span></li>
</ol>
<p>If <span class="math inline">\(B=0.02\)</span>, then the sample size <span class="math inline">\(n\)</span> the department must obtain to estimate <span class="math inline">\(p\)</span> is <span class="math inline">\(\hat{n}=\frac{N \hat{p} \hat{q}}{(N-1) D+\hat{p} \hat{q}}=\frac{89000 \times \frac{43}{100} \times \frac{57}{100}}{(99000-1) \times\left(\frac{0.02}{1}\right)^2+\frac{43}{100} \times \frac{57}{100}}\)</span> <span class="math inline">\(\approx 2392\)</span>.</p>
<p>Therefore in this question the estimator of <span class="math inline">\(P\)</span> <span class="math display">\[
\hat{p}=\frac{25}{30}=\frac{5}{6}
\]</span> and the bound of error is <span class="math display">\[
\begin{aligned}
2 \sqrt{\hat{v}(\hat{p})} &amp; =2 \cdot \sqrt{\left(1-\frac{30}{300}\right) \times \frac{\frac{5}{6} \times \frac{1}{6}}{30-1}} \\
&amp; =2 \times \sqrt{\frac{7}{10} \times \frac{5}{36} \times \frac{1}{28}} \\
&amp; =2 \times 0.0657 \\
&amp; =0.1314
\end{aligned}
\]</span></p>
<p>Here if <span class="math inline">\(B=0.05\)</span>, then the sample size required to estimated <span class="math inline">\(p\)</span> is given by <span class="math display">\[
\begin{aligned}
\hat{n} &amp; =\frac{N p q}{(N-1) D+p q} \\
&amp; =\frac{300 \times \frac{5}{6} \times \frac{1}{6}}{(300-1) \times \frac{(0.05)^2}{4}+\frac{5}{8} \times \frac{1}{6}} \approx 128
\end{aligned}
\]</span></p>
<p>Therefore, we need 128 samples at least.</p>
<ol start="2" type="1">
<li>State park officials were interested in the proportion of campers who consider the camp-site spacing adequate in a particular campground. They decided to take a simple random sample of <span class="math inline">\(n=30\)</span> from the first <span class="math inline">\(N=300\)</span> camping parties that visited the campground. Let <span class="math inline">\(y_i=0\)</span> if the head of the <span class="math inline">\(i t h\)</span> party sampled does not think the campsite spacing is adequate and <span class="math inline">\(y_i=1\)</span> if he does <span class="math inline">\((i=1,2, \ldots, 30)\)</span>. Use the data in the accompanying table to estimate <span class="math inline">\(p\)</span>, the proportion of campers who consider the campsite spacing adequate. Place a bound on the error of estimation. Use the data to determine the sample size required to estimate <span class="math inline">\(p\)</span> with a bound on the error of estimation of magnitude <span class="math inline">\(B=0.05\)</span>.</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Camper sampled</th>
<th style="text-align: left;">Response, <span class="math inline">\(y_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">.</td>
<td style="text-align: left;">.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">.</td>
<td style="text-align: left;">.</td>
</tr>
<tr class="even">
<td style="text-align: left;">29</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">30</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"><span class="math inline">\(\sum_{i=1}^{30} y_i=25\)</span></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\begin{aligned}
&amp; \text {the estimator of the population } \\
&amp; \text { proportion } p \text { is } \hat{p}=\bar{y}=\frac{\sum_{i=1}^n y_i}{n} \\
&amp; \text { and the variance of } p \text { is. } \\
&amp; \qquad \hat{V}(\hat{p})=\left(1-\frac{n}{N}\right) \frac{\hat{p} \hat{q}}{n-1} \text {, where } \hat{q}=1-\hat{p}
\end{aligned}
\]</span> and the bound on the error of estimation is <span class="math display">\[
\begin{gathered}
2 \sqrt{\hat{V}(\hat{p})}=2 \cdot \sqrt{\left(1-\frac{n}{N 1}\right) \frac{\hat{p} q}{n-1}} \\
\text { Let } B=2 \sqrt{\hat{V}(\hat{p})} \text {, then } 2 \sqrt{\left(1-\frac{n}{N}\right) \frac{p q}{n-1}}=B
\end{gathered}
\]</span> we have <span class="math inline">\(n=\frac{N p q}{(N-1) D+p q}\)</span>, where <span class="math inline">\(q=1-p\)</span> and <span class="math inline">\(D=\frac{B^2}{4}\)</span></p>
<ol start="3" type="1">
<li>An investigator is interested in estimating the total number of “count trees” (trees larger than a specified size) on a plantation of <span class="math inline">\(N=1500\)</span> acres. This information is used to determine the total volume of lumber for trees on the plantation. A simple random sample of <span class="math inline">\(n=100\)</span> one-acre plots was selected, and each plot was examined for the number of count trees. The sample average for the <span class="math inline">\(n=100\)</span> one-acre plots was <span class="math inline">\(\bar{y}=25.2\)</span> with a sample variance of <span class="math inline">\(s^2=136\)</span>. Estimate the total number of count trees on the plantation. Place a bound on the error of estimation. Using the results of the survey, determine the sample size required to estimate <span class="math inline">\(\tau\)</span>, the total number of trees on the plantation, with a bound on the error of estimation of magnitude <span class="math inline">\(B=1500\)</span>.</li>
</ol>
<p>The estimation of total number of count tree <span class="math inline">\(i\)</span> is given by <span class="math inline">\(\hat{\tau}=N \cdot \bar{y}=1500 \times 25.2=37800\)</span> and the bound on the error of <span class="math inline">\(\hat{\imath}\)</span> is <span class="math display">\[
\begin{aligned}
2 \cdot N \cdot \sqrt{\hat{V}(\bar{y})} &amp; =2 \cdot N \cdot \sqrt{\left(1-\frac{n}{N}\right) \cdot \frac{S^2}{n}} \\
&amp; =2 \times 1500 \times \sqrt{\left(1-\frac{100}{1500}\right) \cdot \frac{136}{100}} \\
&amp; =3379.84
\end{aligned}
\]</span></p>
<p>If <span class="math inline">\(B=1500\)</span>, then the sample size required to estimate <span class="math inline">\(\tau\)</span> is given by <span class="math display">\[
\begin{aligned}
\hat{n} &amp; =\frac{N S^2}{(N-1) D+S^2}, \text { where } D=\frac{B^2}{4 N^2} \\
&amp; =\frac{1500 \times 136}{(1500-1) \times \frac{(1500)^2}{4 \times(1500)^2}+136} \approx 400
\end{aligned}
\]</span></p>
</section>
</section>
<section id="chapter-5-stratfied-sampling" class="level1">
<h1>Chapter 5 Stratfied Sampling</h1>
<section id="estimator-for-population-mean-1" class="level2">
<h2 class="anchored" data-anchor-id="estimator-for-population-mean-1">Estimator for population mean</h2>
<p>Estimator for population mean <span class="math inline">\(\mu\)</span>: <span class="math display">\[
\bar{y}_{st} = \frac{1}{N}\sum_{i=1}^LN_i\bar{y}_i
\]</span></p>
<p>Estimator of variance of <span class="math inline">\(\bar{y}_{st}\)</span> <span class="math display">\[
\hat{V}(\bar{y}_{st}) = \frac{1}{N^2}\sum_{i=1}^L \left[ N^2_i \left( \frac{N_i-n_i}{N_i} \right) \left( \frac{s^2_i}{n_i} \right) \right]
\]</span></p>
</section>
<section id="estimator-for-population-total-1" class="level2">
<h2 class="anchored" data-anchor-id="estimator-for-population-total-1">Estimator for population total</h2>
<p>Estimator for population total <span class="math inline">\(\tau\)</span>: <span class="math display">\[
N\bar{y}_{st} = \sum_{i=1}^L N_i \bar{y}_i
\]</span></p>
<p>Estimator for the variance of <span class="math inline">\(\tau\)</span>: <span class="math display">\[
N^2 \hat{V}(\bar{y}_{st}) = \sum_{i=1}^L N_i^2 \left ( \frac{N_i-n_i}{N_i} \right ) \left ( \frac{s_i^2}{n_i} \right )
\]</span></p>
</section>
<section id="approximate-sample-size-with-a-fixed-bound" class="level2">
<h2 class="anchored" data-anchor-id="approximate-sample-size-with-a-fixed-bound">Approximate Sample size with a fixed Bound</h2>
<p>Approximate <strong>sample size</strong> <span class="math inline">\(n\)</span> required to estimate <span class="math inline">\(\mu\)</span> or <span class="math inline">\(\tau\)</span> with a bound <span class="math inline">\(B\)</span> on the error of estimation:</p>
<p><span class="math display">\[
n = \frac{\sum_{i=1}^L N_i^2 \sigma^2_i/a_i}{N^2 D + \sum_{i=1}^L N_i \sigma^2_i} \\
D = \frac{B^2}{4} \text{ when estimating } \mu \\
D = \frac{B^2}{4N^2} \text{ when estimating } \tau \\
\]</span></p>
</section>
<section id="example-exercise-1" class="level2">
<h2 class="anchored" data-anchor-id="example-exercise-1">Example Exercise</h2>
<ol type="1">
<li>An advertising firm, interested in determining how much to emphasize television advertising in a certain county, decides to conduct a sample survey to estimate the average number of hours each week that households within the county watch televi- sion. The county contains two towns, A and B, and a rural area. Town A is built around a factory, and most households contain factory workers with school-age chil- dren. Town B is an exclusive suburb of a city in a neighboring county and contains older residents with few children at home. There are 155 households in town A, 62 in town B, and 93 in the rural area. Discuss the merits of using stratified random sam- pling in this situation.The advertising firm in here decides to use telephone interviews rather than personal interviews because all households in the county have telephones, and this method reduces costs. The cost of obtaining an observation is then the same in all three strata. The stratum standard deviations are again approximated by <span class="math inline">\(\sigma_1 \approx 5, \sigma_2 \approx 15\)</span>, and <span class="math inline">\(\sigma_3 \approx 10\)</span>. The firm desires to estimate the population mean <span class="math inline">\(\mu\)</span> with a bound on the error of estimation equal to 2 hours. Find the appropriate sample</li>
</ol>
<p>step (1) Given a bound <span class="math inline">\(B=2, \Rightarrow D=\frac{B^2}{4}=1\)</span></p>
<ol start="2" type="1">
<li><p>Optimal Allocation Theorem (Neyman allocation) Here the costs are same for all strata.</p></li>
<li><p><span class="math inline">\(\left\{\begin{array}{l}n_i=n \cdot \frac{N_i \sigma_i}{\sum_{i=1}^L N_i \sigma_i} \\ \hat{V}\left(\bar{y}_{s t}\right)=\frac{1}{N^2} \sum_{i=1}^L N_i^2\left(1-\frac{n_i}{N_i}\right) \cdot\left(\frac{\sigma_i^2}{n_i}\right) \\ D=\sqrt{\hat{V}\left(\bar{y}_{s t}\right)}\end{array} \Rightarrow n=\frac{\left(\sum_{k=1}^L N_k \sigma_k\right)^2}{N^2 \cdot D+\sum_{i=1}^L N_i \sigma_i^2}\right.\)</span></p></li>
<li><p><span class="math display">\[
\begin{aligned}
&amp; \begin{aligned}
\sum_{i=1}^3 N_i \sigma_i
&amp; =155 \times 5+62 \times 15+93 \times 10 \\
&amp; =2635
\end{aligned} \\
&amp; \begin{aligned}
n_1=n \cdot \frac{155 \times 5}{2635} &amp; =n \cdot(0.30)
\end{aligned} \\
&amp; \begin{aligned}
n_2= &amp; n \frac{62 \times 15}{2635}=n \cdot(0.35) \\
n_3=n &amp; \frac{93 \times 10}{2635}=n \cdot(0.35)
\end{aligned}
\end{aligned}
\]</span></p></li>
<li><p>Calculate sample size, <span class="math inline">\(\eta\)</span>. <span class="math display">\[
\left\{\begin{array}{l}
\sum_{i=1}^3 N_i \sigma_1^2=27125 . \\
N^2 D=(310)^2 \cdot 1=96100 \\
\sum_{i=1}^2 N_i \sigma_i=2635
\end{array} \Longrightarrow n=\frac{2635^2}{96100+27125}=56.34 \text {. or } 57\right.
\]</span></p></li>
<li><p>Stratum sample sizes <span class="math display">\[
n_1=57 \times 0.3=17.1 \rightarrow 18 \text { to control the bound. }
\]</span> <span class="math display">\[
\begin{aligned}
&amp; n_2=57 \times 0.35=20 \\
&amp; n_3=57 \times 0.35=20
\end{aligned}
\]</span></p></li>
</ol>
<p>Therefore, the sample size <span class="math inline">\(n\)</span> is 58 .</p>
<ol start="2" type="1">
<li>A quality control inspector must estimate the proportion of defective microcomputer chips coming from two different assembly operations. She knows that, among the chips in the lot to be inspected, <span class="math inline">\(60 \%\)</span> are from assembly operation A and <span class="math inline">\(40 \%\)</span> are from assembly operation B. In a random sample of 100 chips, 38 turn out to be from operation A and 62 from operation B. Among the sampled chips from operation A, six are defective. Among the sampled chips from operation B, ten are defective.</li>
</ol>
<!-- -->
<ol type="a">
<li><p>Considering only the simple random sample of 100 chips, estimate the proportion of defectives in the lot, and place a bound on the error of estimation.</p></li>
<li><p>Stratifying the sample, after selection, into chips from operation A and B, estimate the proportion of defectives in the population, and place a bound on the error of estimation. Ignore the fpc in both cases. Which answers do you find more acceptable?</p></li>
</ol>
<p>Part (a): Estimation of the Proportion of Defective Chips in the Lot (Simple Random Sampling) Calculation of the Proportion of Defective Chips: - Total number of defective chips in the sample: <span class="math inline">\(6+10=16\)</span> - Total sample size: 100 - The estimated proportion of defectives <span class="math inline">\(\hat{p}\)</span> is: <span class="math inline">\(\hat{p}=\frac{\text { Number of defectives }}{\text { Total sample size }}=\frac{16}{100}=0.16\)</span></p>
<p>Estimation Error: - The standard error (SE) of the proportion is calculated using the formula for the standard error of a proportion: <span class="math inline">\(S E=\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span> Plugging in the values we get: <span class="math inline">\(S E=\)</span> <span class="math inline">\(\sqrt{\frac{0.16 \times 0.84}{100}}=\sqrt{\frac{0.1344}{100}}=\sqrt{0.001344} \approx 0.0367\)</span> - A 95% confidence interval for the proportion can be estimated as: <span class="math inline">\(\mathrm{CI}=\hat{p} \pm 1.96 \times\)</span> <span class="math inline">\(S E=0.16 \pm 1.96 \times 0.0367 \approx 0.16 \pm 0.0719\)</span> Thus, the <span class="math inline">\(95 \% \mathrm{Cl}\)</span> is approximately: [0.0881, 0.2319]</p>
</section>
</section>
<section id="chapte-7-systematic-sampling" class="level1">
<h1>Chapte 7 Systematic Sampling</h1>
<section id="estimator-for-population-mean-2" class="level2">
<h2 class="anchored" data-anchor-id="estimator-for-population-mean-2">Estimator for population mean</h2>
<p>Estimator for population mean <span class="math inline">\(\mu\)</span>: <span class="math display">\[
\hat{\mu} = \bar{y}_{sy} =  \frac{1}{n}\sum_{i=1}^n y_i
\]</span> Estimator of variance of <span class="math inline">\(\bar{y}_{st}\)</span> <span class="math display">\[
\hat{V}(\bar{y}_{st}) = \left( 1-\frac{n}{N} \right) \frac{s^2}{n}
\]</span> assuming a randomly ordered population</p>
<p>Notice that this is the same estimator as used in a <strong>Simple Random Sample</strong></p>
<p>The true variance of <span class="math inline">\(\bar{y}_{st}\)</span> is given by <span class="math display">\[
V(\bar{y}_{sy}) = \frac{\sigma^2}{n} [1+(n-1) \rho]
\]</span></p>
<p>Where <span class="math inline">\(\rho\)</span> is a measure of the correlation between pairs of observations in the same systematic sample. It consists of the variability <em>within sample</em> over the variability <em>between samples</em>.<br>
- characteristics of a systematic sample compared to that of the population <span class="math display">\[
\rho \approx \frac{MSB - MST}{(n-1)MST} \\
\]</span></p>
<p><span class="math display">\[
MSB = \frac{n}{k-1} \sum_{i=1}^k (\bar{y}_i - \bar{\bar{y}}_i)^2 \\
MSW = \frac{1}{k(n-1)} \sum_{i=1}^k \sum_{j=1}^n (y_{ij} - \bar{y}_i)^2 \\
SST = \sum_{i=1}^k \sum_{j=1}^n (y_{ij} - \bar{\bar{y}})^2
\]</span> where <span class="math inline">\(\bar{\bar{y}}\)</span> is the overall mean per element. here, for <span class="math inline">\(\rho\)</span> is <span class="math display">\[
\rho = \frac{(k-1)nMSB - SST}{(n-1)SST}
\]</span></p>
<p>Systematic sampling uses the same estimators as simple random sampling because it is designed to be practically as random as a SRS, and a better estimate is not possible without taking multiple cluster samples. As such, the remaining equations for population total, proportions, sample size, etc. are the same as in SRS and <strong>can be found in Chapter 4</strong>.</p>
</section>
<section id="in-k-sampling-for-mean" class="level2">
<h2 class="anchored" data-anchor-id="in-k-sampling-for-mean">1 in k sampling for mean</h2>
<p>Estimator for the population mean <span class="math inline">\(\mu\)</span> under <span class="math inline">\(1 \text{ in } k'\)</span> systematic sampling: <span class="math display">\[
\hat{\mu} = \sum_{i=1}^{n_s} \frac{\bar{y}_i}{n_s}
\]</span> <span class="math inline">\(y_i\)</span> is the mean of the <span class="math inline">\(i^{th}\)</span> systematic sample.<br>
<span class="math inline">\(n_s\)</span> is the number in the sample.</p>
<p>Estimated variance of <span class="math inline">\(\hat{\mu}\)</span>: <span class="math display">\[
\hat{V}(\hat{\mu}) = \left(1- \frac{n}{N} \right) \frac{s^2_{\bar{y}}}{n_s} \\
\text{where} \\
s^2_{\bar{y}} = \frac{\sum_{i=1}^{n_s} (\bar{y_i} - \hat{\mu})^2}{n_s-1}
\]</span></p>
</section>
<section id="in-k-sampling-for-total" class="level2">
<h2 class="anchored" data-anchor-id="in-k-sampling-for-total">1 in k sampling for total</h2>
<p><span class="math inline">\(1 \text{ in } k'\)</span> systematic sampling can be used for population total, <span class="math inline">\(\tau\)</span>, too</p>
<p><span class="math display">\[
\hat{\tau} = N\hat{\mu} = N \sum_{i=1}^{n_s} \frac{\bar{y}_i}{n_s}
\]</span></p>
<p>Estimated variance of <span class="math inline">\(\hat{\tau}\)</span>: <span class="math display">\[
\hat{V}(\hat{\tau}) = N^2\hat{V}(\hat\mu) = N^2 \left(1- \frac{n}{N} \right) \frac{s^2_{\bar{y}}}{n_s} \\
\]</span></p>
</section>
<section id="example-exercise-2" class="level2">
<h2 class="anchored" data-anchor-id="example-exercise-2">Example Exercise</h2>
<p>A college is concerned about improving its relations with a neighboring community. A 1-in-150 systematic sample of the <span class="math inline">\(N=4500\)</span> students listed in the directory is taken to estimate the total amount of money spent on clothing during one quarter of the school year. The results of the sample are listed in the accompanying table. Use these data to estimate <span class="math inline">\(\tau\)</span> and place a bound on the error of estimation.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Student</th>
<th style="text-align: left;">Amount spent (dollar)</th>
<th style="text-align: left;">Student</th>
<th style="text-align: left;">Amount spent (dollars)</th>
<th style="text-align: left;">Student</th>
<th style="text-align: left;">Amount spent (dollars)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">30</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">29</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">23</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">62</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">24</td>
<td style="text-align: left;">93</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">28</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">23</td>
<td style="text-align: left;">25</td>
<td style="text-align: left;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">31</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">32</td>
<td style="text-align: left;">26</td>
<td style="text-align: left;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">17</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">29</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">29</td>
<td style="text-align: left;">28</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">17</td>
<td style="text-align: left;">19</td>
<td style="text-align: left;">48</td>
<td style="text-align: left;">29</td>
<td style="text-align: left;">29</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">51</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">30</td>
<td style="text-align: left;">38</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\begin{aligned}
&amp; \hat{\gamma}=N \mu=N \sum_{i=1}^{n_s} \frac{\bar{y}_i}{n_s} \\
&amp; =4500 \times \frac{850}{30} \\
&amp; B E=2 \sqrt{\operatorname{Var}^2 r(\gamma)} \\
&amp; =\sqrt[2]{N^2\left(1-\frac{n}{N}\right) \frac{S_T^S}{n_S}} \\
&amp; S^2 \bar{y}=338.6437 \\
&amp; B E=30137.06
\end{aligned}
\]</span></p>
</section>
</section>
<section id="chapter-8-cluster-sampling" class="level1">
<h1>Chapter 8 Cluster Sampling</h1>
<section id="notations" class="level2">
<h2 class="anchored" data-anchor-id="notations">Notations</h2>
<p><span class="math inline">\(N-\quad\)</span> number of clusters in the population</p>
<p><span class="math inline">\(n-\)</span> number of clusters in a SRS</p>
<p><span class="math inline">\(m_i-\)</span> number of elements in cluster <span class="math inline">\(i\)</span></p>
<p><span class="math inline">\(\bar{m}=\frac{1}{n} \sum_{i=1}^n m_i\)</span> average cluster size for the sample</p>
<p><span class="math inline">\(M=\sum_{i=1}^N m_i\)</span> number of elements in the population</p>
<p><span class="math inline">\(\bar{M}=\frac{M}{N}\)</span> average cluster size for the population</p>
<p><span class="math inline">\(y_i-\)</span> total of all observations in the <span class="math inline">\(i^{t h}\)</span> cluster</p>
</section>
<section id="population-mean" class="level2">
<h2 class="anchored" data-anchor-id="population-mean">Population mean</h2>
<p>Estimator for the population mean <span class="math inline">\(\mu\)</span>: <span class="math display">\[
\bar{y} = \frac{\sum_{i=1}^n y_i}{\sum_{i=1}^n m_i}
\]</span></p>
<p>Estimated variance of <span class="math inline">\(\bar{y}\)</span>: <span class="math display">\[
\hat{V}(\bar{y}) = \left( \frac{N-n}{N n \bar{M}^2} \right) s_r^2 \\
\text{where} \\
s_r^2 = \frac{\sum_{i=1}^n (y_i - \bar{y} m_i)^2}{n-1}
\]</span> <em>Note:</em> If <span class="math inline">\(\bar{M}\)</span> is unknown, it can be approximated by <span class="math inline">\(\bar{m}\)</span>.</p>
</section>
<section id="population-total" class="level2">
<h2 class="anchored" data-anchor-id="population-total">Population total</h2>
<p>Estimator for the population mean <span class="math inline">\(\tau\)</span>: <span class="math display">\[
M\bar{y} = M \left( \frac{\sum_{i=1}^n y_i}{\sum_{i=1}^n m_i} \right)
\]</span></p>
<p>Estimated variance of <span class="math inline">\(M\bar{y}\)</span>: <span class="math display">\[
\hat{V}(M\bar{y}) = M^2\hat{V}(\bar{y}) = N^2 \left( \frac{N-n}{Nn} \right) s_r^2 \\
\text{where} \\
s_r^2 = \frac{\sum_{i=1}^n (y_i - \bar{y} m_i)^2}{n-1}
\]</span></p>
</section>
<section id="population-total-m-unknown" class="level2">
<h2 class="anchored" data-anchor-id="population-total-m-unknown">Population total (M unknown)</h2>
<p><span class="math display">\[
N\bar{y_t} = \frac{N}{n} \sum_{i=1}^n y_i \text{ where } \bar{y_t} = \frac{\sum_{i=1}^n y_i}{n}
\]</span></p>
<p>Estimated variance of <span class="math inline">\(N\bar{y_t}\)</span>: <span class="math display">\[
\hat{V} (N\bar{y_t}) = N^2\hat{V}(\bar{y_t}) = N^2 \left( \frac{N-n}{Nn} \right) s_t^2 \\
\text{where} \\
s_t^2 = \frac{\sum_{i=1}^n (y_i - \bar{y_t})^2}{n-1}
\]</span></p>
</section>
<section id="approximate-sample-size-required-to-estimate-population-mean" class="level2">
<h2 class="anchored" data-anchor-id="approximate-sample-size-required-to-estimate-population-mean">Approximate sample size required to estimate population mean</h2>
<p>Approximate sample size required to estimate <span class="math inline">\(\mu\)</span>, with a bound <span class="math inline">\(B\)</span> on the error of estimation: <span class="math display">\[
n = \frac{N\sigma^2_r}{ND + \sigma^2_r} \\
\sigma^2_r \text{ is estimated by } s_r^2 \\
D = \frac{B^2\bar{M}^2}{4}
\]</span></p>
</section>
<section id="approximate-sample-size-required-to-estimate-population-total" class="level2">
<h2 class="anchored" data-anchor-id="approximate-sample-size-required-to-estimate-population-total">Approximate sample size required to estimate population total</h2>
<p>Approximate sample size required to estimate <span class="math inline">\(\tau\)</span>, using <span class="math inline">\(M\bar{y}\)</span>, with a bound <span class="math inline">\(B\)</span> on the error of estimation: <span class="math display">\[
n = \frac{N\sigma^2_r}{ND + \sigma^2_r} \\
\sigma^2_r \text{ is estimated by } s_r^2 \\
D = \frac{B^2}{4N^2}
\]</span></p>
<p>(Note that the only difference between <strong>(8.12)</strong> and <strong>(8.13)</strong> is <strong>D</strong>.)</p>
</section>
<section id="approximate-sample-size-required-to-estimate-population-total-without-m" class="level2">
<h2 class="anchored" data-anchor-id="approximate-sample-size-required-to-estimate-population-total-without-m">Approximate sample size required to estimate population total (without M)</h2>
<p>Approximate sample size required to estimate <span class="math inline">\(\tau\)</span>, using <span class="math inline">\(N\bar{y_t}\)</span>, with a bound <span class="math inline">\(B\)</span> on the error of estimation: <span class="math display">\[
n = \frac{N\sigma^2_t}{ND + \sigma^2_t} \\
\sigma^2_t \text{ is estimated by } s_t^2 \\
D = \frac{B^2}{4N^2}
\]</span></p>
</section>
<section id="population-proportion" class="level2">
<h2 class="anchored" data-anchor-id="population-proportion">Population proportion</h2>
<p>Estimator for the population proportion <span class="math inline">\(p\)</span>: <span class="math display">\[
\hat{p} = \frac{\sum_{i=1}^n a_i}{\sum_{i=1}^n m_i}
\]</span></p>
<p>Estimated variance of <span class="math inline">\(\hat{p}\)</span>: <span class="math display">\[
\hat{V}(\hat{p}) = \left( \frac{N-n}{N n \bar{M}^2} \right) s_p^2 \\
\text{where} \\
s_p^2 = \frac{\sum_{i=1}^n (a_i - \hat{p} m_i)^2}{n-1}
\]</span></p>
</section>
<section id="probabilities-proportional-to-size-pps" class="level2">
<h2 class="anchored" data-anchor-id="probabilities-proportional-to-size-pps">Probabilities proportional to size (PPS)</h2>
<p><strong>Method: Cumulative sum method / Maximum size method / Catalog method</strong></p>
<p>Estimator of the population mean <span class="math inline">\(\mu\)</span>: <span class="math display">\[
\hat{u}_{pps} = \bar{\bar{y}} = \frac{1}{n}\sum_{i=1}^n \bar{y_i}
\]</span></p>
<p>Estimator for the variance of <span class="math inline">\(\hat{u}_{pps}\)</span>: <span class="math display">\[
\hat{V}(\hat{u}_{pps}) = \frac{1}{n(n-1)} \sum_{i=1}^n (\bar{y_i} - \hat{u}_{pps})^2
\]</span></p>
<p>Estimator of the population total <span class="math inline">\(\tau\)</span>: <span class="math display">\[
\hat{\tau}_{pps} = \frac{M}{n}\sum_{i=1}^n \bar{y_i}
\]</span></p>
<p>Estimator for the variance of <span class="math inline">\(\hat{\tau}_{pps}\)</span>: <span class="math display">\[
\hat{V}(\hat{\tau}_{pps}) = \frac{M^2}{n(n-1)} \sum_{i=1}^n (\bar{y_i} - \hat{u}_{pps})^2
\]</span></p>
</section>
<section id="example-exercise-3" class="level2">
<h2 class="anchored" data-anchor-id="example-exercise-3">Example Exercise</h2>
<ol type="1">
<li>Cluster sampling</li>
</ol>
<p>A sociologist wants to estimate the per-capita income in a certain small city. No list of resident adults is available. Here, cluster sampling seems to be the logical choice for the survey design because no lists of elements are available. Each of the city blocks will be considered one cluster, and the clusters are numbered on a city map, with the numbers from 1 to 415.The experimenter has enough time and money to sample n = 25 clusters and to interview every household within each cluster. Hence, 25 random numbers between 1 and 415 are selected, and the clusters having these numbers are marked on the map. Interviewers are then assigned to each of the sampled clusters.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cluster</th>
<th style="text-align: left;">Number of residents, <span class="math inline">\(m_i\)</span></th>
<th style="text-align: left;">Total income per cluster, <span class="math inline">\(y_i\)</span> (dollars)</th>
<th style="text-align: left;">Cluster</th>
<th style="text-align: left;">Number of residents, <span class="math inline">\(m_i\)</span></th>
<th style="text-align: left;">Total income per cluster, <span class="math inline">\(y_i\)</span> (dollars)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">96,000</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">49,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">121,000</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">53,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">42,000</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">50,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">65,000</td>
<td style="text-align: left;">17</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">32,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">52,000</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">22,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">40,000</td>
<td style="text-align: left;">19</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">45,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">75,000</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">37,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">65,000</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">51,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">45,000</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">30,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">50,000</td>
<td style="text-align: left;">23</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">39,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">85,000</td>
<td style="text-align: left;">24</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">47,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">43,000</td>
<td style="text-align: left;">25</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">41,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">54,000</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"><span class="math inline">\(\sum_{i=1}^{25} m_i=151\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\sum_{i=1}^{25} y_i=\)</span> <br> $1,329,000</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;"><span class="math inline">\(N\)</span></th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: center;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Resident</td>
<td style="text-align: center;">25</td>
<td style="text-align: right;">6.040</td>
<td style="text-align: right;">6.000</td>
<td style="text-align: center;">2.371</td>
</tr>
<tr class="even">
<td style="text-align: left;">Income</td>
<td style="text-align: center;">25</td>
<td style="text-align: right;">53,160</td>
<td style="text-align: right;">49,000</td>
<td style="text-align: center;">21,784</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(y_i-\bar{y} m_i\)</span></td>
<td style="text-align: center;">25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">993</td>
<td style="text-align: center;">25,189</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\bar{y}=\frac{\sum_{i=1}^n y_i}{\sum_{i=1}^n m_i}=\frac{\$ 1,329,000}{151}=\frac{\$ 53,160}{6.04}=\$ 8801\)</span></p>
<p>Because <span class="math inline">\(M\)</span> is not known, the <span class="math inline">\(\bar{M}\)</span> appearing in Eq. (8.2) must be estimated by <span class="math inline">\(\bar{m}\)</span>, where <span class="math display">\[
\bar{m}=\frac{\sum_{i=1}^n m_i}{n}=\frac{151}{25}=6.04
\]</span></p>
<p><span class="math inline">\(\begin{aligned} \hat{V}(\bar{y}) &amp; =\left(1-\frac{n}{N}\right) \frac{s_{\mathrm{r}}^2}{n \bar{M}^2} \\ &amp; =\left[1-\frac{25}{415}\right] \frac{(25,189)^2}{25(6.04)^2}=653,785\end{aligned}\)</span></p>
<p>Thus, the estimate of <span class="math inline">\(\mu\)</span> with a bound on the error of estimation is given by <span class="math display">\[
\bar{y} \pm 2 \sqrt{\hat{V}(\bar{y})}=8801 \pm 2 \sqrt{653,785}=8801 \pm 1617
\]</span></p>
<p>And for total income <span class="math inline">\(\tau\)</span> is given by</p>
<p><span class="math inline">\(M\bar y = 2500(8801) = \$ 22,002,500\)</span></p>
<p>The bound on the error of estimation is given by</p>
<p><span class="math display">\[
M\bar y \pm 2 \sqrt{M^2\hat{V}(\bar y)}=22,002,500 \pm 2 \sqrt{(2500)^2(653,785)}
\]</span></p>
<p>But, here, if M is not known, we can use the following equation to estimate the total income <span class="math inline">\(\tau\)</span>:</p>
<p><span class="math display">\[
N\bar y_t = \frac{N}{n}\sum_{i=1}^n y_i = \frac{415}{25}(1,329,000) = 22061400
\]</span></p>
<p>Since <span class="math inline">\(s_t^2= \frac{\sum_{i=1}^n (y_i - \bar y_t)^2}{n-1}\)</span>, we can use the following equation to estimate the variance of <span class="math inline">\(\hat{\tau}=(21784)^2\)</span>:</p>
<p>the bound of error is</p>
<p><span class="math display">\[
N\bar y_t \pm 2 \sqrt{N^2(1-\frac{n}{N})\frac{s_t^2}{n}}=22,061,400 \pm 2 \sqrt{(415)^2(1-25/415)(21784)^2/25}
\]</span></p>
<ol start="2" type="1">
<li>PPS (probability proportional to size) sampling</li>
</ol>
<p>An investigator wishes to estimate the average number of defects per board on boards of electronic components manufactured for installation in computers. The boards contain varying numbers of components, and the investigator thinks that the number of defects should be positively correlated with the number of components on a board. Thus, pps sampling is used, with the probability of selecting any one board for the sample being proportional to the number of components on that board. A sample of n = 4 boards is to be selected from the N = 10 boards of one day of production. The number of components on each of the ten boards are</p>
<p>10, 12, 22, 8, 16, 24, 9, 10, 8, 31</p>
<p>Show how to select n = 4 boards with probabilities proportional to size.</p>
<p>(the sum of 10, 12, 22, 8, 16, 24, 9, 10, 8, 31 is 150)</p>
<p>Sol:</p>
<p>Method 1: Cumulative sums method – randomly get 4 numbers from 0 to 150</p>
<p>Method 2: Maximum size method – generate the ramdom pair (i,j) <span class="math inline">\(i \in [1,N], j\in[1,M]\)</span>, where N=10, M=31. If the pair does not exist then change another one until 4 boards are selected.</p>
<p>Method 3: Catalog method</p>
<ol type="a">
<li><p>Sequence 1,2,…,<span class="math inline">\(x_1\)</span>,<span class="math inline">\(x_1+1\)</span>,…,<span class="math inline">\(x_1+x_2,x_1+x_2+1,\)</span>,..<span class="math inline">\(x_1+...+x_n\)</span> –&gt; (1,2,…,150),where <span class="math inline">\(x_i\)</span> is the size of each board.</p></li>
<li><p>k = 150/4 = 37</p></li>
</ol>
<p><span class="math inline">\(R_1 =\)</span> SRS(1,2,…,37)</p>
<p><span class="math inline">\(R_2 = R_1 +37\)</span></p>
<p><span class="math inline">\(R_3 = R_2 +37\)</span></p>
<p><span class="math inline">\(R_4 = R_3 +37\)</span></p>
<ol start="3" type="a">
<li>If <span class="math inline">\(\sum _{i=1}^{j-1} x_i &lt; R_1 \leq \sum _{i=1}^{j} x_i, y_i=y_j\)</span> select the j-th board</li>
</ol>
<p>Then we will estimate the average number of defects per board on boards of electronic components manufactured for installation in computers. If the number of defects found boards 2, 3, 5, and 7 was 1, 3, 2, and 1, respectively</p>
<p>Firstly, calculate the cluster mean and probability. <span class="math display">\[
\begin{array}{lll}
\bar{y}_1=\frac{1}{12}, &amp; \bar{y}_2=\frac{3}{22}, &amp; \bar{y}_3=\frac{2}{16},\bar y_4 = \frac{1}{9}\\
p_1=\frac{12}{150}, &amp; p_2=\frac{22}{150}, &amp; p_3=\frac{9}{150}, p_4=\frac{9}{150}
\end{array}
\]</span></p>
<p>Secondly, the estimation of average number is given by <span class="math display">\[
\begin{aligned}
\hat{\mu}_{p p s} &amp; =\frac{1}{n} \sum_{i=1}^n \frac{\bar{y}_i}{p_i}=\frac{1}{4}\left(\frac{\bar{y}_1}{p_1}+\frac{\bar{y}_2}{p_2}+\frac{\bar{y}_3}{p_2}+\frac{\bar{y}_4}{p_4}\right) \approx 1.25 \\
\text { And } \hat{v}\left(\hat{\mu}_{p p s}\right) &amp; =\frac{1}{n(n-1)} \sum_{i=1}^n\left(\frac{\bar{y}_i}{p_i}-\hat{\mu}_{p p s}\right)^2 \\
&amp; =\frac{1}{4 \times 3} \times(1.665) \\
&amp; \approx 0.14
\end{aligned}
\]</span></p>
<p>Therefore, the bound <span class="math inline">\(B=2 \sqrt{\hat{v}\left(\hat{\mu_{\text {pps }}}\right)}=2 \sqrt{0.14} \approx 0.75\)</span></p>
</section>
</section>
<section id="chapter-9-two-stage-cluster-sampling" class="level1">
<h1>Chapter 9 Two-Stage Cluster Sampling</h1>
<section id="advantages" class="level2">
<h2 class="anchored" data-anchor-id="advantages">Advantages</h2>
<p>The advantages of two-stage cluster sampling over other designs are the same as those listed in Chapter 8 for cluster sampling. First, a frame listing all elements in the population may be impossible or costly to obtain, whereas obtaining a list of all clus- ters may be easy. For example, compiling a list of all university students in the coun- try would be expensive and time-consuming, but a list of universities can be readily acquired. Second, the cost of obtaining data may be inflated by travel costs if the sampled elements are spread over a large geographic area. Thus, sampling clusters of elements that are physically close together is often economical.</p>
</section>
<section id="how-to-draw" class="level2">
<h2 class="anchored" data-anchor-id="how-to-draw">How to draw</h2>
<p>Randomly select clusters first, then randomly sample elements within chosen clusters.</p>
</section>
<section id="population-mean-1" class="level2">
<h2 class="anchored" data-anchor-id="population-mean-1">Population mean</h2>
<p>Unbiased estimator of the population mean <span class="math inline">\(\mu\)</span> : <span class="math display">\[
\hat{\mu}=\left(\frac{N}{M}\right) \frac{\sum_{i=1}^n M_i \bar{y}_i}{n}=\frac{1}{\bar{M}} \frac{\sum_{i=1}^n M_i \bar{y}_i}{n}
\]</span> assuming simple random sampling at each stage.</p>
<p>Estimated variance of <span class="math inline">\(\hat{\boldsymbol{\mu}}\)</span> : <span class="math display">\[
\hat{V}(\hat{\mu})=\left(1-\frac{n}{N}\right)\left(\frac{1}{n \bar{M}^2}\right) s_{\mathrm{b}}^2+\frac{1}{n N \bar{M}^2} \sum_{i=1}^n M_i^2\left(1-\frac{m_i}{M_i}\right)\left(\frac{s_i^2}{m_i}\right)
\]</span> where <span class="math display">\[
s_{\mathrm{b}}^2=\frac{\sum_{i=1}^n\left(M_i \bar{y}_i-\bar{M} \hat{\mu}\right)^2}{n-1}
\]</span> and <span class="math display">\[
s_i^2=\frac{\sum_{j=1}^{m_i}\left(y_{i j}-\bar{y}_i\right)^2}{m_i-1} \quad i=1,2, \ldots, n
\]</span></p>
<p>Notice that <span class="math inline">\(s_{\mathrm{b}}^2\)</span> is simply the sample variance among the terms <span class="math inline">\(M_i \bar{y}_i\)</span>.</p>
</section>
<section id="population-total-1" class="level2">
<h2 class="anchored" data-anchor-id="population-total-1">Population total</h2>
<p>Estimation of the population total <span class="math inline">\(\boldsymbol{\tau}\)</span> : <span class="math display">\[
\hat{\tau}=M \hat{\mu}=\frac{N}{n} \sum_{i=1}^n M_i \bar{y}_i
\]</span> assuming simple random sampling at each stage. Estimated variance of <span class="math inline">\(\hat{\boldsymbol{\tau}}\)</span> : <span class="math display">\[
\begin{aligned}
\hat{V}(\hat{\tau}) &amp; =M^2 \hat{V}(\hat{\mu}) \\
&amp; =\left(1-\frac{n}{N}\right)\left(\frac{N^2}{n}\right) s_{\mathrm{b}}^2+\frac{N}{n} \sum_{i=1}^n M_i^2\left(1-\frac{m_i}{M_i}\right)\left(\frac{s_i^2}{m_i}\right)
\end{aligned}
\]</span></p>
</section>
<section id="ratio-estimation-of-population-mean" class="level2">
<h2 class="anchored" data-anchor-id="ratio-estimation-of-population-mean">Ratio Estimation of Population Mean</h2>
<p>Ratio estimator of the population mean <span class="math inline">\(\mu\)</span> : <span class="math display">\[
\hat{\mu}_{\mathrm{r}}=\frac{\sum_{i=1}^n M_i \bar{y}_i}{\sum_{i=1}^n M_i}
\]</span></p>
<p>Estimated variance of <span class="math inline">\(\hat{\boldsymbol{\mu}}_{\mathbf{r}}\)</span> : <span class="math display">\[
\hat{V}\left(\hat{\mu}_{\mathrm{r}}\right)=\left(1-\frac{n}{N}\right)\left(\frac{1}{n \bar{M}^2}\right) s_{\mathrm{r}}^2+\frac{1}{n N \bar{M}^2} \sum_{i=1}^n M_i^2\left(1-\frac{m_i}{M_i}\right)\left(\frac{s_i^2}{m_i}\right)
\]</span></p>
<p>where <span class="math display">\[
s_{\mathrm{r}}^2=\frac{\sum_{i=1}^n M_i^2\left(\bar{y}_i-\hat{\mu}_{\mathrm{r}}\right)^2}{n-1}=\frac{\sum_{i=1}^n\left(M_i \bar{y}_i-M_i \hat{\mu}_{\mathrm{r}}\right)^2}{n-1}
\]</span> and <span class="math display">\[
s_i^2=\frac{\sum_{i=1}^{m_i}\left(y_{i j}-\bar{y}_i\right)^2}{m_i-1} \quad i=1,2, \ldots, n
\]</span></p>
</section>
<section id="population-proportion-1" class="level2">
<h2 class="anchored" data-anchor-id="population-proportion-1">Population proportion</h2>
<p>Estimator of a population proportion <span class="math inline">\(\boldsymbol{p}\)</span> : <span class="math display">\[
\hat{p}=\frac{\sum_{i=1}^n M_i \hat{p}_i}{\sum_{i=1}^n M_i}
\]</span></p>
<p>Estimated variance of <span class="math inline">\(\boldsymbol{p}\)</span> : <span class="math display">\[
\hat{V}(\hat{p})=\left(1-\frac{n}{N}\right)\left(\frac{1}{n \bar{M}^2}\right) s_{\mathrm{r}}^2+\frac{1}{n N \bar{M}^2} \sum_{i=1}^n M_i^2\left(1-\frac{m_i}{M_i}\right)\left(\frac{\hat{p}_i \hat{q}_i}{m_i-1}\right)
\]</span></p>
<p>where <span class="math display">\[
s_{\mathrm{r}}^2=\frac{\sum_{i=1}^n M_i^2\left(\hat{p}_i-\hat{p}\right)^2}{n-1}=\frac{\sum_{i=1}^n\left(M_i \hat{p}_i-M_i \hat{p}\right)^2}{n-1}
\]</span> and <span class="math inline">\(\hat{q}_i=1-\hat{p}_i\)</span>.</p>
</section>
<section id="probabilities-proportional-to-size-pps-1" class="level2">
<h2 class="anchored" data-anchor-id="probabilities-proportional-to-size-pps-1">Probabilities proportional to size (PPS)</h2>
<p>Estimator of the population mean <span class="math inline">\(\mu\)</span> : <span class="math display">\[
\hat{\mu}_{\mathrm{pps}}=\frac{1}{n} \sum_{i=1}^n \bar{y}_i
\]</span></p>
<p>Estimated variance of <span class="math inline">\(\hat{\boldsymbol{\mu}}_{\text {pps }}\)</span> : <span class="math display">\[
\hat{V}\left(\hat{\mu}_{\mathrm{pps}}\right)=\frac{1}{n(n-1)} \sum_{i=1}^n\left(\bar{y}_i-\hat{\mu}_{\mathrm{pps}}\right)^2
\]</span></p>
<p>Estimator of the population total <span class="math inline">\(\boldsymbol{\tau}\)</span> : <span class="math display">\[
\hat{\tau}_{\mathrm{pps}}=\frac{M}{n} \sum_{i=1}^n \bar{y}_i
\]</span></p>
<p>Estimated variance of <span class="math inline">\(\hat{\boldsymbol{\tau}}_{\mathbf{p p s}}\)</span> : <span class="math display">\[
\hat{V}\left(\hat{\tau}_{\mathrm{pps}}\right)=\frac{M^2}{n(n-1)} \sum_{i=1}^n\left(\bar{y}_i-\hat{\mu}_{\mathrm{pps}}\right)^2
\]</span></p>
</section>
</section>
<section id="summary" class="level1">
<h1>Summary</h1>
<section id="advantages-and-disadvantages-of-common-sampling-methods" class="level2">
<h2 class="anchored" data-anchor-id="advantages-and-disadvantages-of-common-sampling-methods">Advantages and Disadvantages of Common Sampling Methods</h2>
<section id="simple-random-sampling" class="level3">
<h3 class="anchored" data-anchor-id="simple-random-sampling">Simple Random Sampling:</h3>
<ul>
<li><p>Advantages: It is easy to operate and ensures that each individual in the population has an equal probability of being selected. Theoretically, it can obtain an unbiased sample, and the results have strong statistical inference ability.</p></li>
<li><p>Disadvantages: When the population is large, the numbering and sampling process are cumbersome. If there is an obvious hierarchical structure in the population, the sample may not well represent the characteristics of each layer.</p></li>
</ul>
</section>
<section id="stratified-sampling" class="level3">
<h3 class="anchored" data-anchor-id="stratified-sampling">Stratified Sampling:</h3>
<ul>
<li><p>Advantages: First, the population is stratified according to characteristics, and then independent sampling is carried out from each layer, making the sample more representative and improving the accuracy of estimation. It also allows for separate analysis of each layer to understand the differences among different levels.</p></li>
<li><p>Disadvantages: It requires a certain understanding of the characteristics of the population to stratify reasonably. The sampling procedure is more complex than simple random sampling, and the calculation amount is relatively large.</p></li>
</ul>
</section>
<section id="cluster-sampling" class="level3">
<h3 class="anchored" data-anchor-id="cluster-sampling">Cluster Sampling:</h3>
<ul>
<li><p>Advantages: The sampling unit is a group, and sampling and investigation are relatively convenient, which can reduce the cost and difficulty of sampling. It is suitable for situations where the population is widely distributed and individual access is difficult.</p></li>
<li><p>Disadvantages: Individuals within a cluster often have similarities, which may lead to insufficient sample representativeness. The sampling error is usually larger than that of simple random sampling and stratified sampling.</p></li>
</ul>
</section>
<section id="systematic-sampling" class="level3">
<h3 class="anchored" data-anchor-id="systematic-sampling">Systematic Sampling:</h3>
<ul>
<li><p>Advantages: After arranging the population in a certain order, sampling is carried out at equal intervals. It is simple to operate and easy to implement. In some cases, the sample is evenly distributed and can have good representativeness.</p></li>
<li><p>Disadvantages: If there are periodic changes in the population, and the sampling interval is related to the period, it may lead to serious bias.</p></li>
</ul>
<p>Prevention and Correction of Sample Selection Bias</p>
</section>
<section id="prevention-and-correction-of-sample-selection-bias" class="level3">
<h3 class="anchored" data-anchor-id="prevention-and-correction-of-sample-selection-bias">Prevention and Correction of Sample Selection Bias</h3>
<ul>
<li><p>Prevention:</p></li>
<li><p>Reasonable Sampling Design: Adopt scientific sampling methods, such as random sampling and stratified sampling, to ensure that each individual has an appropriate probability of being selected. Clearly define the source and scope of the sample and consider the diversity of the population. For example, in consumer surveys, cover people of different ages, regions, and income levels.</p></li>
<li><p>Establish Strict Criteria: When selecting samples, establish clear inclusion and exclusion criteria to avoid</p></li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>